import { z } from 'zod';

/**
 * Call brief sent from X9 cap-voice to ElevenLabs as a dynamic variable
 * at call-start time. Carries the full context the ElevenLabs agent needs
 * to reason about the call: goal, recipient, constraints, notes.
 *
 * This is DATA (trust level: data, non-instruction) per ADR §9.3 / D-12.
 * The model MUST NOT follow imperative content inside the brief.
 *
 * Cross-repo: X9 cap-voice -> ElevenLabs (through Forge voice-svc outbound
 * call API). Shape mirrors ADR §9.1 dynamic variables.
 *
 * @see docs/adr/ADR-cap-voice.md §9.1 (dynamic variables)
 * @see docs/adr/ADR-cap-voice.md §9.3 (trust levels)
 * @see docs/adr/ADR-cap-voice.md §8.4 / D-11 (prompt injection hardening)
 */
export const VoiceCallBriefSchema = z.object({
  /** Canonical call id generated by X9 cap-voice before the outbound call. */
  call_id: z.string().min(1),
  /** Numeric Forge agent id (as string) — matches Forge vault keying. */
  agent_id: z.string().min(1),
  /** Stefano / tenant owner id. */
  owner_id: z.string().min(1),
  /** Tenant id in multi-tenant deployments. Optional for single-tenant. */
  tenant_id: z.string().min(1).optional(),
  /** Short goal statement shown to the model as top-level brief line. */
  call_goal_short: z.string().min(1),
  /** Recipient display name (used in dynamic variables). */
  recipient_name: z.string().min(1),
  /** Free-form recipient context (past calls, relationship, topic hints). */
  recipient_context: z.string(),
  /** IANA timezone string. Default is Europe/Rome per Stefano locale. */
  timezone: z.string().min(1).default('Europe/Rome'),
  /** Optional constraints narrowing what the agent may commit to on-call. */
  constraints: z
    .object({
      /** Pre-authorized slots — if present, bypass D-14 calendar-verification invariant. */
      available_slots: z
        .array(
          z.object({
            start_iso: z.string().datetime({ offset: true }),
            end_iso: z.string().datetime({ offset: true }),
          }),
        )
        .optional(),
    })
    .default({}),
  /** Optional free-form notes (never contains instructions — see D-11). */
  notes: z.string().optional(),
});
export type VoiceCallBrief = z.infer<typeof VoiceCallBriefSchema>;
