import { z } from 'zod';
import { VoiceCallBriefSchema } from './brief.js';
import { AuthorizedActionsSchema } from './authorized-actions.js';

/**
 * Request sent by X9 (agent-core or cap-voice tool layer) to cap-voice to
 * initiate an outbound call. cap-voice then composes dynamic variables and
 * hands off to ElevenLabs.
 *
 * @see docs/adr/ADR-cap-voice.md §13 (tool surface)
 * @see docs/adr/ADR-cap-voice.md §9 (dynamic variables)
 */
export const VoiceCallStartRequestSchema = z.object({
  /** Canonical call id generated by the caller (must be unique per call). */
  call_id: z.string().min(1),
  /** Target E.164 phone number. Normalization done caller-side. */
  recipient_phone: z.string().min(1),
  /** Full call brief — trust level: data (per D-12). */
  brief: VoiceCallBriefSchema,
  /** Server-enforced authorization matrix for this call. */
  authorized_actions: AuthorizedActionsSchema,
  /** Prompt artifact version pin (e.g. "outbound-call/v1.it"). */
  prompt_version: z.string().min(1),
  /** Optional locale override (otherwise derived from prompt_version). */
  locale: z.string().min(1).optional(),
});
export type VoiceCallStartRequest = z.infer<typeof VoiceCallStartRequestSchema>;

/**
 * Response from cap-voice after the outbound call is initiated (ElevenLabs
 * acknowledged + voice_sessions row registered in Forge).
 */
export const VoiceCallStartResponseSchema = z.object({
  /** Echoes the call_id from the request. */
  call_id: z.string().min(1),
  /** ElevenLabs conversation id (unique per call). */
  conversation_id: z.string().min(1),
  /** ElevenLabs agent id (the conversational agent, not the Forge agent). */
  elevenlabs_agent_id: z.string().min(1),
  /** RFC-3339 timestamp when cap-voice acknowledged the outbound init. */
  started_at: z.string().datetime({ offset: true }),
});
export type VoiceCallStartResponse = z.infer<typeof VoiceCallStartResponseSchema>;
