import type { AgentModelsConfiguration, AgentModelsState, AgentModelRuntimeAttestation, AgentModelsOverview, AgentModelsBatchRequest, AgentModelsBatchPreview, AgentModelsBatchResult } from '@x9-forge/contracts/model-router';
import { AgentModelsStateSchema, isAgentModelApplyConfirmed, isAgentModelsBatchResultConsistent, sameAgentModelsBatchRequest } from '@x9-forge/contracts';
import type { ForgeModelsAccess, ForgeModelsProgress } from '@x9-forge/contracts/http';
import { forgeModelsBatchContract, isAgentModelsBatchWithinAccess } from '@x9-forge/contracts/http';
declare const config: AgentModelsConfiguration;
declare const state: AgentModelsState;
declare const runtime: AgentModelRuntimeAttestation;
declare const overview: AgentModelsOverview;
declare const request: AgentModelsBatchRequest;
declare const preview: AgentModelsBatchPreview;
declare const result: AgentModelsBatchResult;
declare const access: ForgeModelsAccess;
declare const progress: ForgeModelsProgress;
const parsed: AgentModelsState = AgentModelsStateSchema.parse(state);
const applied: boolean = isAgentModelApplyConfirmed(config, {}, {}, runtime);
const replay: boolean = sameAgentModelsBatchRequest(request, request);
const consistent: boolean = isAgentModelsBatchResultConsistent(request, preview, result);
const authorized: boolean = isAgentModelsBatchWithinAccess(request, overview, access);
const path: '/api/models/batch' = forgeModelsBatchContract.path;
const authentication: 'forge-session' = forgeModelsBatchContract.authentication;
void [replay, parsed, applied, consistent, authorized, path, authentication, progress];
