import pathlib,subprocess,json,hashlib,re,difflib,sys
R=pathlib.Path('/Users/admintemp/Downloads/Claude/x9-forge-contract-bridge-codex-180-1');P=pathlib.Path('/private/tmp/codex-a-chiavi-completamento/proofs/34-24/source-cuts-extra');P.mkdir(exist_ok=True)
ENV={'HOME':'/Users/admintemp','PATH':'/Users/admintemp/.nvm/versions/node/v24.14.1/bin:/usr/bin:/bin:/usr/sbin:/sbin','TMPDIR':'/private/tmp','CI':'1','NO_COLOR':'1'};C=[]
def add(name,file,old,new,test,pattern=None):C.append(dict(name=name,file=file,old=old,new=new,test=test,pattern=pattern))
def guard(name,file,message,test,pattern=None):
 hits=[x for x in (R/file).read_text().splitlines() if 'if (' in x and "message: '"+message+"'" in x];assert len(hits)==1,(name,hits)
 line=hits[0];i=line.index('if (');end=line.index(') ctx.addIssue');add(name,file,line,line[:i]+'if (false'+line[end:],test,pattern)
a='src/model-router/agent-model-configuration.ts';e='src/model-router/model-consumer-execution.ts';s='src/model-router/capability-model-settings.ts';b='src/model-router/models-batch.ts';m='src/agent/agent-management.ts';c='tests/model-router/chiavi-model-composition.test.ts';initial='tests/model-router/agent-model-initial-source.test.ts';defs='tests/model-router/c5-model-consumers.test.ts';exe='tests/model-router/c5-model-consumer-execution.test.ts';obs='tests/model-router/c5-model-source-observation.test.ts';legacy='tests/model-router/model-consumer-legacy-observation.test.ts';overview='tests/model-router/models-overview-coverage.test.ts';cmd='tests/agent/c5-model-configuration-command.test.ts'
for name,message in [('runtime-binding','Source scope names its runtime exactly'),('validity-window','Source validity ends after observation'),('complete-slot-partition','Every registered slot is present or missing exactly once'),('no-missing-or-all-excluded','Complete means no missing consumer'),('canonical-consumer-settings','Source settings must match the canonical consumer and its requirements'),('state-exact-identity','Initial source belongs to this state identity'),('state-no-saved-version','Initial source cannot claim a saved or applied version'),('state-no-competing-authority','Initial source cannot coexist with another model authority')]:guard('initial-'+name,a,message,initial)
add('initial-roleless-strict',a,'export const AgentModelInitialSourceSchema = ModelInitialSourceBaseSchema.superRefine(checkLoadedModelSource);','export const AgentModelInitialSourceSchema = ModelInitialSourceBaseSchema.loose().superRefine(checkLoadedModelSource);',c,'C04')
add('initial-complete-vault-identity','src/model-router/agent-model-configuration-values.ts','vaultAgentId: z.number().int().positive(),','vaultAgentId: z.number().int().positive().optional(),',c,'C06')
add('initial-fresh-time',a,"if (source.coverage !== 'complete' || source.selections.length === 0 || !Number.isFinite(time) || time < Date.parse(source.observedAt) - 5_000 || time >= Date.parse(source.validUntil)) return false;","if (source.coverage !== 'complete' || source.selections.length === 0) return false;",c,'C08')
add('initial-generation-identity-scope',a,'return source.sourceVersion === expectation.sourceVersion && sameModelAgentIdentity(source.identity, expectation.identity) && sameCapabilityScope(source.scope, expectation.scope);','return true;',c,'C06|C07|C08')
for name,message in [('runtime-binding','Observed model source scope must name its runtime identity'),('time-order','Observed source validity must end after observation'),('saved-provenance','Modern source observation requires saved scoped model authority'),('state-identity','Observed source belongs to this state identity'),('state-scope','Observed source belongs to the saved model scope')]:guard('modern-source-'+name,a,message,obs)
add('modern-source-freshness',a,'if (!Number.isFinite(time) || time < observed - 5_000 || time > observed + 60_000 || time >= Date.parse(source.validUntil)) return false;','if (false) return false;',obs)
for name,message,test in [('install-registered','Install exactly the registered consumer selection',exe),('runtime-scoped','Consumer scope names the addressed runtime',exe),('readback-registered-slot','Unknown consumer cannot attest installation',c),('readback-validity','Readback validity ends after observation',exe),('readback-public-reason','Non-installed state has a sanitized reason',legacy),('readback-registered-settings','Readback must match the registered consumer',legacy),('installed-complete-proof','Installed requires actual selection, version and request',exe),('observed-actual-settings','Observed requires actual legacy selection',c),('observed-no-version','Observed cannot claim an installed config version',c),('observed-no-request','Observed cannot claim an installation request',c),('active-vector-space','Readback must use the active vector space',legacy),('rebuild-before-install','Rebuild must complete before target installation',exe),('installed-receipt-matches','Installed receipt identifies the actually completed request',exe),('pending-never-installed','Pending/failed receipt must not claim target installed',exe),('read-request-registered','Read only a registered consumer',c)]:guard('consumer-'+name,e,message,test)
add('consumer-current-cas-authority',e,'return request.success && source.success && request.data.expectedSourceVersion === source.data.sourceVersion && sameModelAgentIdentity(request.data.identity, source.data.identity) && sameCapabilityScope(request.data.scope, source.data.scope);','return request.success && source.success;',exe)
add('consumer-confirm-freshness',e,"if (receipt.outcome !== 'installed' || state.status !== 'installed' || !Number.isFinite(time) || time < Date.parse(state.observedAt) - 5_000 || time >= Date.parse(state.validUntil)) return false;","if (receipt.outcome !== 'installed' || state.status !== 'installed') return false;",legacy)
add('consumer-confirm-request-version-slot',e,'if (receipt.requestId !== request.requestId || state.requestId !== request.requestId || state.configVersion !== request.configVersion || state.slotId !== request.slotId) return false;','if (false) return false;',exe)
add('consumer-confirm-identity-scope-settings',e,'return sameModelAgentIdentity(request.identity, state.identity) && sameCapabilityScope(request.scope, state.scope) && sameCapabilityModelSettings(request.settings, state.settings);','return true;',exe)
add('consumer-route-slot-binding',e,'return path.success && request.success && path.data.slotId === request.data.slotId;','return path.success && request.success;',exe)
guard('single-embedding-dimension',s,'Single embedding selection requires its vector dimension only',defs)
guard('failover-no-embedding',s,'Embedding cannot fail over into a different vector space',c)
add('single-selection-position',s,"if (settings.mode === 'single') return [{ tier: 'primary', descriptor: settings.descriptor }];","if (settings.mode === 'single') return [{ tier: 'fallback', descriptor: settings.descriptor }];",defs,'S01')
add('failover-selection-order',s,"if (settings.mode === 'failover') return [{ tier: 'primary', descriptor: settings.primary }, { tier: 'fallback', descriptor: settings.fallback }];","if (settings.mode === 'failover') return [{ tier: 'fallback', descriptor: settings.fallback }, { tier: 'primary', descriptor: settings.primary }];",defs,'S02')
add('catalog-embedding-dimension',s,"if (settings.mode === 'single' && settings.function === 'embedding' && entry.embeddingDimensions !== settings.embeddingDimensions) issues.add('embedding-dimension-mismatch');","if (false) issues.add('embedding-dimension-mismatch');",defs,'S07')
add('catalog-vision-search-support',s,'(settings.requirements.vision === true && entry.features.vision !== true) || (settings.requirements.webSearch === true && entry.features.webSearch !== true) || ','',defs,'S06')
for name,message in [('unknown-provenance','Unknown provenance is readonly without a claimed Master'),('complete-no-missing','Complete inventory has no missing slots or reason'),('incomplete-public-reason','Incomplete inventory requires a public reason'),('missing-slots-unique','Duplicate missing slot'),('exact-identity','Inconsistent agent identity'),('owner-binding','An agent has exactly one owner'),('unique-coverage','Duplicate agent coverage'),('present-missing-disjoint','A slot cannot be both present and missing'),('cross-namespace-identity','Ambiguous agent identities'),('vault-identity','Ambiguous vault identities')]:guard('overview-'+name,b,message,overview)
add('overview-owner-coverage-access','src/http/endpoints/forge-models.ts','[...overview.data.rows, ...(overview.data.coverage ?? [])]','overview.data.rows',c,'C13')
add('writer-coverage-request-scoped',b,"if (coverage !== undefined && coverage.status !== 'complete') issues.add('slot-unavailable');","if (false) issues.add('slot-unavailable');",overview,'W04')
add('writer-unrelated-coverage-does-not-block',b,'const coverage = overview.coverage?.find(entry => sameModelAgentIdentity(entry.identity, agent.identity));',"const coverage = overview.coverage?.find(entry => entry.status !== 'complete');",overview,'W01|W03')
add('command-version-cas',m,'if (command.modelConfiguration?.configVersion !== undefined && command.modelConfiguration.configVersion !== command.desiredVersion) {','if (false) {',cmd,'D06')
add('command-observed-generation-required',m,'if ((command.modelConfiguration !== undefined) !== (command.modelExpectedSourceVersion !== undefined)) {','if (false) {',cmd,'D07')
add('command-bootstrap-generation-matches',m,'if (command.modelConfiguration !== undefined && command.modelBootstrap !== undefined && command.modelExpectedSourceVersion !== command.modelBootstrap.expectedSourceVersion) {','if (false) {',cmd,'D07')
add('command-replay-full-semantic-identity',m,'JSON.stringify(canonicalCommandValue(a.modelConfiguration)) === JSON.stringify(canonicalCommandValue(b.modelConfiguration))','true',cmd,'D02|D03|D11|D12')

C=[]
add('registry-detached-definitions','src/model-router/model-consumers.ts','return structuredClone(definitions);','return definitions;',defs,'R03')
add('registry-detached-lookup','src/model-router/model-consumers.ts',"const found = definitions.find(consumer => consumer.slotId === slotId);\n  return found === undefined ? undefined : structuredClone(found);","const found = definitions.find(consumer => consumer.slotId === slotId);\n  return found;",defs,'R02')
add('registry-required-metadata','src/model-router/model-consumers.ts',"}).strict();\nexport type ModelConsumerDefinition", "}).partial().strict();\nexport type ModelConsumerDefinition",defs,'R06')
add('registry-feature-types','src/model-router/model-catalog.ts','vision: z.boolean().optional(), webSearch: z.boolean().optional()','vision: z.unknown().optional(), webSearch: z.unknown().optional()',defs,'S10')
add('runtime-exact-position-count',a,'if (actual.selections.length !== saved.selections.reduce((count, slot) => count + modelSettingsSelections(slot.settings).length, 0)) return false;','if (false) return false;',exe,'M03|M08')
add('runtime-vector-dimension',a,"const dimensionMatches = slot.settings.mode !== 'single' || slot.settings.function !== 'embedding' || selection?.embeddingDimensions === slot.settings.embeddingDimensions;",'const dimensionMatches = true;',exe,'M04')
add('runtime-exact-selection-metadata',a,'return selection !== undefined && dimensionMatches && selection.capability === slot.settings.capability && selection.function === slot.settings.function && sameModelDescriptor(selection.descriptor, descriptor);','return selection !== undefined && dimensionMatches;',exe,'M02')
add('apply-confirm-explicit-authority',a,'if (!authority.success || !sameAgentCommand(request, { ...request, modelConfiguration: authority.data })) return false;','if (false) return false;',cmd,'D16')
add('command-direct-generation-authority',a,'return command.data.modelExpectedSourceVersion === source.data.sourceVersion && sameModelAgentIdentity(configuration.identity, source.data.identity) && sameCapabilityScope(configuration.provenance.scope, source.data.scope);','return true;',cmd,'D13')
line=next(line for line in (R/m).read_text().splitlines() if 'if (consumer === undefined || selection.settings.capability' in line)
add('command-registered-consumer-authority',m,line,'    if (false) {',cmd,'D17|D18')
add('local-http-required-auth','src/http/endpoints/internal-agent-model-source-observation.ts',"authType: 'secret' as const","authType: 'none' as const",'tests/model-router/agent-model-local-source-http.test.ts')
add('public-model-execution-export','src/model-router/index.ts',"export * from './model-consumer-execution.js';",'',c,'C01')

if len(sys.argv)>1:
 P=P/sys.argv[1];P.mkdir(exist_ok=True);C=[case for case in C if case['name'] in sys.argv[2:]]
(P/'matrix-input.json').write_text(json.dumps(C,indent=2)+'\n')
def run(case,phase):
 command=['pnpm','exec','vitest','run','--config','/private/tmp/codex-a-chiavi-completamento/bridge.config.mjs',case['test'],'--maxWorkers=1']
 if case['pattern']:command+=['-t',case['pattern']]
 result=subprocess.run(command,cwd=R,env=ENV,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True);out=re.sub(r'\x1b\[[0-9;]*m','',result.stdout);(P/(case['name']+'-'+phase+'.log')).write_text('$ '+json.dumps(command)+'\n'+out+'\nEXIT_CODE='+str(result.returncode)+'\n');return result.returncode,out
results=[]
for case in C:
 f=R/case['file'];before=f.read_bytes();text=before.decode();count=text.count(case['old']);expected=2 if case['name']=='initial-generation-identity-scope' else 1
 if count!=expected:raise RuntimeError((case['name'],'replacement count',count))
 changed=text.replace(case['old'],case['new'],1).encode();originalhash=hashlib.sha256(before).hexdigest();(P/(case['name']+'.diff')).write_text(''.join(difflib.unified_diff(text.splitlines(True),changed.decode().splitlines(True),fromfile=case['file'],tofile=case['file'])))
 try:
  f.write_bytes(changed);code,out=run(case,'red');semantic=code!=0 and 'AssertionError' in out and 'TypeError:' not in out and 'SyntaxError:' not in out
 finally:f.write_bytes(before)
 restored=hashlib.sha256(f.read_bytes()).hexdigest();assert restored==originalhash
 green,gout=run(case,'restored-green');item={**{k:case[k] for k in ('name','file','test','pattern')},'red_exit':code,'semantic_red':semantic,'restore_sha256':restored,'original_sha256':originalhash,'fresh_green_exit':green,'red_summary':re.findall(r'Tests\s+.*',out),'green_summary':re.findall(r'Tests\s+.*',gout)};results.append(item);(P/'matrix-results.json').write_text(json.dumps(results,indent=2)+'\n');print(case['name'],semantic,green,flush=True)
 if green!=0:raise RuntimeError(('restored baseline failed',case['name']))
print('CUTS_CAUGHT',sum(x['semantic_red'] for x in results),'/',len(results),flush=True);sys.exit(0 if all(x['semantic_red'] for x in results) else 1)
