import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const mode = process.argv[2];
const name = '@x9-forge/contracts';
const load = async subpath => mode === 'cjs' ? require(name + subpath) : import(name + subpath);
const pkg = JSON.parse(fs.readFileSync(new URL('./node_modules/@x9-forge/contracts/package.json', import.meta.url), 'utf8'));
let available = 0;
for (const key of Object.keys(pkg.exports)) { const mod = await load(key === '.' ? '' : key.slice(1)); assert.ok(Object.keys(mod).length); available++; }
const p = await load('/capability/paperclip');
const c = await load('/capability');
const h = await load('/http');
const a = await load('/agent');
const id = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const ids = { companyId: id(1), paperclipAgentId: id(2), runId: id(3), issueId: id(4) };
const scope = { tenantId: 'tenant-a', ownerId: 'owner-a', agentId: 'agent-a' };
const metadata = { ...ids, admissionId: id(5), challenge: 'a'.repeat(64), hostIssuedAt: '2026-10-09T17:00:00.000Z', hostDeadlineAt: '2026-10-09T17:01:00.000Z' };
const prepared = { phase: 'prepared', ...metadata };
const receipt = { kind: 'paperclip.x9-run-binding', schemaVersion: 1, ...metadata };
const execution = { capability: 'paperclip', source: 'x9_native_admission', scope, configVersion: 2, provisioningRevision: 3, sessionId: 'host-session', ...metadata };
const readback = { scope, appliedVersion: 2, enabled: true, provisioningRevision: 3, unitId: 'unit-a', callerRoleRef: 'developer', ...{companyId:ids.companyId,paperclipAgentId:ids.paperclipAgentId}, roleAgents: {}, provenance: { source: 'native_operator_inventory', inventoryFingerprint: 'b'.repeat(64) }, registryFingerprint: 'c'.repeat(64), configFingerprint: 'd'.repeat(64) };
const call = { callId: 'call-a', tool: 'paperclip_queue', input: {}, ...scope, sessionId: 'host-session', configVersion: 2, executionContext: execution, credentials: { PAPERCLIP_API_KEY: 'synthetic-native-value' } };
let cases = 0;
const check = fn => { fn(); cases++; };
check(() => assert.equal(p.PAPERCLIP_API_KEY, 'PAPERCLIP_API_KEY'));
check(() => assert.equal(p.PAPERCLIP_X9_ADAPTER_SECRET, 'PAPERCLIP_X9_ADAPTER_SECRET'));
check(() => assert.deepEqual(p.PaperclipNativeRunReceiptSchema.parse(receipt), receipt));
check(() => assert.equal(p.matchesPaperclipReceipt(prepared, receipt), true));
check(() => assert.equal(p.matchesPaperclipReceipt(prepared, { ...receipt, challenge: 'f'.repeat(64) }), false));
check(() => assert.equal(p.PaperclipNativeRunReceiptSchema.safeParse({ ...receipt, challenge: undefined }).success, false));
check(() => assert.equal(p.matchesPaperclipExecution(readback, execution), true));
check(() => assert.equal(p.matchesPaperclipExecution(readback, { ...execution, provisioningRevision: 4 }), false));
check(() => assert.equal(p.isPaperclipHostWindowOpen(execution, Date.parse(metadata.hostDeadlineAt)), false));
check(() => assert.deepEqual(c.PaperclipToolCallRequestSchema.parse(call), call));
check(() => assert.equal(c.PaperclipToolCallRequestSchema.safeParse({ ...call, executionContext: undefined }).success, false));
check(() => assert.equal(c.PaperclipToolCallRequestSchema.safeParse({ ...call, credentials: { ...call.credentials, PAPERCLIP_RUN_ID: ids.runId } }).success, false));
check(() => assert.equal(c.PaperclipToolCallRequestSchema.safeParse({ ...call, tenantId: 'other' }).success, false));
check(() => assert.deepEqual(c.toPaperclipToolCallScope(readback, execution), { ...scope, sessionId: execution.sessionId, configVersion: 2, executionContext: execution }));
const turn = { channelId: 'paperclip', sessionId: 'correlation', message: 'Synthetic work' };
check(() => assert.deepEqual(h.InternalAgentTurnRequestSchema.parse({ ...turn, paperclipAdmission: { phase: 'prepare', native: ids } }).paperclipAdmission, { phase: 'prepare', native: ids }));
check(() => assert.deepEqual(h.InternalAgentTurnResponseSchema.parse({ ok: true, reply: '', updatedHistory: [], paperclipAdmission: prepared }).paperclipAdmission, prepared));
check(() => assert.equal(h.InternalAgentTurnResponseSchema.safeParse({ ok: true, reply: 'model work', updatedHistory: [], paperclipAdmission: prepared }).success, false));
check(() => assert.deepEqual(h.InternalAgentTurnRequestSchema.parse(turn), turn));
check(() => assert.equal(h.paperclipAgentInstallPath('agent-a'), '/internal/capability/agents/agent-a/install'));
check(() => assert.equal(a.AgentContextCoreSchema.safeParse({ agentId: 'agent-a', ownerId: 'owner-a', credentials: {}, llmConfig: { provider: 'test', model: 'test' }, telegramAllowFrom: [] }).success, true));
console.log(JSON.stringify({ mode, availableSubpaths: available, semanticCases: cases }));
