import { describe, expect, it } from 'vitest';
import type { z } from 'zod';
import * as router from '../../src/model-router/index.js';
const api = router as unknown as { AgentModelsConfigurationSchema: z.ZodType; AgentModelsStateSchema: z.ZodType; AgentContextWithModelsSchema: z.ZodType; AgentModelRuntimeAttestationSchema: z.ZodType; isAgentModelApplyConfirmed: (config: unknown, command: unknown, result: unknown, attestation: unknown, now?: Date) => boolean };
const identity = { managementAgentId: 'agent-42', runtimeAgentId: 'runtime-42', vaultAgentId: 42 };
const descriptor = { provider: 'openai', modelId: 'synthetic-model', protocol: 'responses', adapterId: 'synthetic-adapter' };
const settings = { capability: 'agent-core', function: 'reasoning', catalogVersion: 'catalog-1', requirements: { tools: true, stream: true, structuredOutput: false }, mode: 'pin', pin: descriptor, tiers: { standard: descriptor, advanced: descriptor, reasoning: descriptor }, fallback: descriptor };
const config = () => ({ schemaVersion: 1, identity: { ...identity }, configVersion: 4, selections: [{ slotId: 'agent_chat', settings }] });
const now = new Date('2026-10-07T16:30:00Z');
const command = () => ({ action: 'apply-config', requestId: 'request-0042', desiredVersion: 4 });
const result = () => ({ ok: true, agentId: 'agent-42', identity: { ...identity }, action: 'apply-config', requestId: 'request-0042', replayed: false, outcome: 'ok', requestedVersion: 4, versions: { desired: 4, applied: 4, failed: null }, results: [{ target: { kind: 'runtime', targetId: 'runtime-42' }, outcome: 'ok' }], completedAt: now.toISOString() });
const attestation = () => ({ identity: { ...identity }, configVersion: 4, requestId: 'request-0042', observedAt: now.toISOString(), selections: ['standard', 'advanced', 'reasoning', 'fallback'].map(tier => ({ slotId: 'agent_chat', capability: 'agent-core', function: 'reasoning', tier, descriptor: { ...descriptor } })) });
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const context = () => ({ agentId: 'agent-42', ownerId: 'synthetic-owner', credentials: {}, llmConfig: { provider: 'openai', model: 'legacy-synthetic' }, telegramAllowFrom: [], displayName: 'Synthetic', workspacePath: '/synthetic/workspace', registryPath: '/synthetic/registry', configVersion: 4, modelConfiguration: config() });

describe('versioned agent models', () => {
  it('exports the aggregate, runtime evidence and apply verifier', () => { for (const key of ['AgentModelsConfigurationSchema', 'AgentModelsStateSchema', 'AgentContextWithModelsSchema', 'AgentModelRuntimeAttestationSchema', 'isAgentModelApplyConfirmed']) expect(api[key as keyof typeof api]).toBeDefined(); });
  it('accepts a capability-owned versioned snapshot', () => { expect(api.AgentModelsConfigurationSchema.safeParse(config()).success).toBe(true); });
  it('rejects duplicate stable slots', () => { const value = config(); value.selections.push(value.selections[0]!); expect(api.AgentModelsConfigurationSchema.safeParse(value).success).toBe(false); });
  it.each(['', 'https://synthetic.invalid', 'x'.repeat(65)])('rejects invalid slot id %s', slotId => { const value = config(); value.selections[0]!.slotId = slotId; expect(api.AgentModelsConfigurationSchema.safeParse(value).success).toBe(false); });
  it('rejects unknown schema versions and empty selections', () => { expect(api.AgentModelsConfigurationSchema.safeParse({ ...config(), schemaVersion: 2 }).success).toBe(false); expect(api.AgentModelsConfigurationSchema.safeParse({ ...config(), selections: [] }).success).toBe(false); });
  it('rejects metadata outside the aggregate and selection allowlists', () => { expect(api.AgentModelsConfigurationSchema.safeParse({ ...config(), token: 'synthetic' }).success).toBe(false); const value = clone(config()); Object.assign(value.selections[0]!, { baseUrl: 'synthetic' }); expect(api.AgentModelsConfigurationSchema.safeParse(value).success).toBe(false); });
  it('binds the aggregate to the saved context version and identity', () => { expect(api.AgentContextWithModelsSchema.safeParse(context()).success).toBe(true); const value = context(); value.configVersion = 3; expect(api.AgentContextWithModelsSchema.safeParse(value).success).toBe(false); });
  it('rejects an unversioned explicit model context', () => { const value = context(); delete (value as Partial<typeof value>).configVersion; expect(api.AgentContextWithModelsSchema.safeParse(value).success).toBe(false); });
  it('accepts the declared runtime identity but never another agent', () => { const value = context(); value.agentId = 'runtime-42'; expect(api.AgentContextWithModelsSchema.safeParse(value).success).toBe(true); value.agentId = 'other'; expect(api.AgentContextWithModelsSchema.safeParse(value).success).toBe(false); });
  it('preserves legacy contexts only when explicit models are absent', () => { const { modelConfiguration: _models, configVersion: _version, ...legacy } = context(); expect(api.AgentContextWithModelsSchema.safeParse(legacy).success).toBe(true); expect(api.AgentContextWithModelsSchema.safeParse({ ...legacy, modelConfiguration: {} }).success).toBe(false); expect(api.AgentContextWithModelsSchema.safeParse({ ...legacy, modelConfiguration: null }).success).toBe(false); });
  it('rejects duplicate runtime slot/tier evidence', () => { const value = attestation(); value.selections.push(value.selections[0]!); expect(api.AgentModelRuntimeAttestationSchema.safeParse(value).success).toBe(false); });
  it('accepts saved and effective snapshots at the canonical versions', () => { expect(api.AgentModelsStateSchema.safeParse({ identity, versions: { desired: 4, applied: 4, failed: null }, saved: config(), runtime: attestation() }).success).toBe(true); });
  it('represents unknown versions and absent evidence without a guessed value', () => { expect(api.AgentModelsStateSchema.safeParse({ identity, versions: null, saved: null, runtime: null }).success).toBe(true); });
  it.each(['saved', 'runtime'])('rejects %s evidence for another identity', key => { const value = { identity, versions: { desired: 4, applied: 4, failed: null }, saved: config(), runtime: attestation() }; value[key as 'saved' | 'runtime'].identity.runtimeAgentId = 'other'; expect(api.AgentModelsStateSchema.safeParse(value).success).toBe(false); });
  it.each(['saved', 'runtime'])('rejects %s evidence at the wrong version', key => { const value = { identity, versions: { desired: 4, applied: 4, failed: null }, saved: config(), runtime: attestation() }; value[key as 'saved' | 'runtime'].configVersion = 3; expect(api.AgentModelsStateSchema.safeParse(value).success).toBe(false); });
});

describe('apply requires actual runtime evidence', () => {
  it('confirms all four selections only for matching version, identity and request', () => { expect(api.isAgentModelApplyConfirmed(config(), command(), result(), attestation(), now)).toBe(true); });
  it('accepts an identical replay without a second apply', () => { expect(api.isAgentModelApplyConfirmed(config(), command(), { ...result(), replayed: true }, attestation(), now)).toBe(true); });
  it.each([null, {}, { ok: true, applied: 1 }])('never treats global success or missing evidence %j as per-agent apply', value => { expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
  it.each(['config', 'command', 'attestation'])('refuses malformed %s', key => { expect(api.isAgentModelApplyConfirmed(key === 'config' ? {} : config(), key === 'command' ? {} : command(), result(), key === 'attestation' ? {} : attestation(), now)).toBe(false); });
  it.each(['managementAgentId', 'runtimeAgentId', 'vaultAgentId'])('matches every identity field %s', key => { const value = clone(attestation()); Object.assign(value.identity, { [key]: key === 'vaultAgentId' ? 43 : 'other' }); expect(api.isAgentModelApplyConfirmed(config(), command(), result(), value, now)).toBe(false); });
  it('requires result identity and the management addressee', () => { const value = result(); delete (value as Partial<typeof value>).identity; expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); expect(api.isAgentModelApplyConfirmed(config(), command(), { ...result(), agentId: 'runtime-42' }, attestation(), now)).toBe(false); });
  it.each(['command', 'result', 'attestation'])('refuses a different %s requestId', key => { const c = command(); const r = result(); const a = attestation(); if (key === 'command') c.requestId = 'other-request'; if (key === 'result') r.requestId = 'other-request'; if (key === 'attestation') a.requestId = 'other-request'; expect(api.isAgentModelApplyConfirmed(config(), c, r, a, now)).toBe(false); });
  it('requires the requested configuration version in the command', () => { expect(api.isAgentModelApplyConfirmed(config(), { ...command(), desiredVersion: 3 }, result(), attestation(), now)).toBe(false); });
  it('requires the attested version', () => { expect(api.isAgentModelApplyConfirmed(config(), command(), result(), { ...attestation(), configVersion: 3 }, now)).toBe(false); });
  it('requires the applied configuration version in the result', () => { const value = result(); value.requestedVersion = 3; value.versions.applied = 3; expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
  it('requires a successful result for the actual runtime target', () => { const value = result(); value.results[0]!.target.targetId = 'other'; expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
  it('does not turn a lifecycle command into an apply', () => { expect(api.isAgentModelApplyConfirmed(config(), { action: 'reload', requestId: 'request-0042' }, result(), attestation(), now)).toBe(false); });
  it('does not accept failed or partial apply', () => { const value = result(); value.outcome = 'error'; value.versions.applied = 3; Object.assign(value.results[0]!, { outcome: 'error', reason: { code: 'timeout' } }); expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
  it('rejects expired, future and invalid clocks', () => { for (const date of [new Date(now.getTime() + 60_001), new Date(now.getTime() - 5001), new Date(NaN)]) expect(api.isAgentModelApplyConfirmed(config(), command(), result(), attestation(), date)).toBe(false); });
  it.each(['standard', 'advanced', 'reasoning', 'fallback'])('requires runtime evidence for %s', tier => { const value = attestation(); value.selections = value.selections.filter(entry => entry.tier !== tier); expect(api.isAgentModelApplyConfirmed(config(), command(), result(), value, now)).toBe(false); });
  it.each(['slotId', 'capability', 'function', 'tier'])('requires exact runtime selection %s', key => { const value = attestation(); Object.assign(value.selections[0]!, { [key]: key === 'tier' ? 'fallback' : key === 'capability' ? 'cap-news' : key === 'function' ? 'tts' : 'other' }); expect(api.isAgentModelApplyConfirmed(config(), command(), result(), value, now)).toBe(false); });
  it.each(['provider', 'modelId', 'protocol', 'adapterId'])('requires the actually installed descriptor field %s', key => { const value = attestation(); Object.assign(value.selections[0]!.descriptor, { [key]: key === 'protocol' ? 'messages' : 'other' }); expect(api.isAgentModelApplyConfirmed(config(), command(), result(), value, now)).toBe(false); });
  it('refuses extra unrelated runtime selections', () => { const value = attestation(); value.selections.push({ ...value.selections[0]!, slotId: 'unrelated' }); expect(api.isAgentModelApplyConfirmed(config(), command(), result(), value, now)).toBe(false); });
});

it('attests distinct automatic tier selections without inferring from model names', () => { const value = clone(config()); Object.assign(value.selections[0]!.settings, { mode: 'automatic' }); delete (value.selections[0]!.settings as Partial<typeof settings>).pin; const actual = attestation(); for (const tier of ['standard', 'advanced', 'reasoning'] as const) { value.selections[0]!.settings.tiers[tier].modelId = 'synthetic-' + tier; actual.selections.find(entry => entry.tier === tier)!.descriptor.modelId = 'synthetic-' + tier; } expect(api.isAgentModelApplyConfirmed(value, command(), result(), actual, now)).toBe(true); const standard = actual.selections[0]!.descriptor; actual.selections[0]!.descriptor = actual.selections[1]!.descriptor; actual.selections[1]!.descriptor = standard; expect(api.isAgentModelApplyConfirmed(value, command(), result(), actual, now)).toBe(false); });
it('requires an actual runtime target even when a channel reports successful apply', () => { const value = result(); value.results[0]!.target.kind = 'channel'; expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
it('rejects runtime metadata outside the allowlist and invalid tier names', () => { expect(api.AgentModelRuntimeAttestationSchema.safeParse({ ...attestation(), token: 'synthetic' }).success).toBe(false); const value = attestation(); Object.assign(value.selections[0]!, { token: 'synthetic' }); expect(api.AgentModelRuntimeAttestationSchema.safeParse(value).success).toBe(false); const tier = attestation(); tier.selections[0]!.tier = 'invented'; expect(api.AgentModelRuntimeAttestationSchema.safeParse(tier).success).toBe(false); });
it('rejects excess configuration slots and runtime selections', () => { expect(api.AgentModelsConfigurationSchema.safeParse({ ...config(), selections: Array.from({ length: 65 }, (_, i) => ({ slotId: 'slot-' + i, settings })) }).success).toBe(false); expect(api.AgentModelRuntimeAttestationSchema.safeParse({ ...attestation(), selections: Array.from({ length: 257 }, (_, i) => ({ ...attestation().selections[0]!, slotId: 'slot-' + i })) }).success).toBe(false); });
it('rejects empty runtime evidence and unknown state fields', () => { expect(api.AgentModelRuntimeAttestationSchema.safeParse({ ...attestation(), selections: [] }).success).toBe(false); expect(api.AgentModelsStateSchema.safeParse({ identity, versions: null, saved: null, runtime: null, baseUrl: 'synthetic' }).success).toBe(false); });

it('matches the result identity independently of the attestation identity', () => { const value = result(); value.identity.runtimeAgentId = 'other-runtime'; expect(api.isAgentModelApplyConfirmed(config(), command(), value, attestation(), now)).toBe(false); });
