import { describe, expect, it } from 'vitest';
import type { z } from 'zod';
import * as API from '../../src/model-router/index.js';
import * as HTTP from '../../src/http/index.js';
import * as Agent from '../../src/agent/index.js';
function exported(name:string):unknown { const value:unknown=Reflect.get(API,name);expect(value,name).toBeDefined();return value; }
function schema(name:string):z.ZodType { return exported(name) as z.ZodType; }
function call(name:string,...args:unknown[]):unknown { return (exported(name) as (...args:unknown[])=>unknown)(...args); }
const identity={managementAgentId:'synthetic-master',runtimeAgentId:'synthetic-runtime',vaultAgentId:71};
const scope={agentId:identity.runtimeAgentId,ownerId:'synthetic-owner',tenantId:'synthetic-tenant'};
const descriptor={provider:'openai',modelId:'synthetic-model',protocol:'chat-completions',adapterId:'synthetic-adapter'};
const settings={capability:'agent-core',function:'reasoning',catalogVersion:'synthetic-catalog',requirements:{tools:false,stream:false,structuredOutput:false},mode:'single',descriptor};
const request={schemaVersion:1,identity,scope,slotId:'agent_classifier',configVersion:1,requestId:'synthetic-request-0001',expectedSourceVersion:'synthetic-generation-1',settings};
const state={schemaVersion:1,identity,scope,slotId:request.slotId,sourceVersion:'synthetic-generation-2',observedAt:'2026-10-09T06:20:00Z',validUntil:'2026-10-09T06:20:30Z',status:'installed',configVersion:1,requestId:request.requestId,settings,reason:null,embedding:null};
const receipt={requestId:request.requestId,outcome:'installed',state};
const now=new Date('2026-10-09T06:20:01Z');
const current={identity,scope,sourceVersion:request.expectedSourceVersion};

describe('C5 consumer installation transport',()=>{
 it('E01 strict detached request and observed state round trip',()=>{ expect(schema('ModelConsumerInstallRequestSchema').safeParse(request).success).toBe(true);expect(schema('ModelConsumerInstallRequestSchema').parse(request)).toEqual(request);expect(schema('ModelConsumerRuntimeStateSchema').parse(state)).toEqual(state);expect(schema('ModelConsumerInstallReceiptSchema').parse(receipt)).toEqual(receipt);expect(call('isModelConsumerInstallConfirmed',request,receipt,now)).toBe(true);expect(call('isModelConsumerInstallRequestCurrent',request,current)).toBe(true); });
 it.each(['identity','scope','slotId','configVersion','requestId','expectedSourceVersion','settings'])('E02 install request requires %s',key=>{const input={...request};Reflect.deleteProperty(input,key);expect(schema('ModelConsumerInstallRequestSchema').safeParse(input).success).toBe(false);});
 it.each([{slotId:'unknown'},{scope:{...scope,agentId:'other'}},{identity:{...identity,vaultAgentId:undefined}},{expectedSourceVersion:' '},{configVersion:0},{settings:{...settings,capability:'memory'}},{settings:{...settings,requirements:{...settings.requirements,structuredOutput:true}}},{settings:{...settings,mode:'automatic',tiers:{},fallback:descriptor}},{extra:true},{credentials:{}},{context:{}}])('E03 rejects unauthorized shape %j',patch=>expect(schema('ModelConsumerInstallRequestSchema').safeParse({...request,...patch}).success).toBe(false));
 it.each([{sourceVersion:'changed'},{identity:{...identity,vaultAgentId:72}},{identity:{...identity,runtimeAgentId:'other'}},{scope:{...scope,ownerId:'other'}},{scope:{...scope,tenantId:'other'}},{scope:{...scope,agentId:'other'}}])('E04 install CAS uses the fresh observed generation %j',patch=>{expect(call('isModelConsumerInstallRequestCurrent',request,{...current,...patch})).toBe(false);});
 it.each([{configVersion:2},{requestId:'other-request'},{identity:{...identity,managementAgentId:'other'}},{identity:{...identity,runtimeAgentId:'other'}},{identity:{...identity,vaultAgentId:72}},{scope:{...scope,ownerId:'other'}},{scope:{...scope,tenantId:'other'}},{slotId:'security_rules'},{settings:{...settings,descriptor:{...descriptor,modelId:'synthetic-other'}}},{settings:null},{status:'unknown'},{status:'pending'},{reason:'unexpected'}])('E05 wrong readback never proves installation %j',patch=>{expect(call('isModelConsumerInstallConfirmed',request,{...receipt,state:{...state,...patch}},now)).toBe(false);});
 it.each([{requestId:'other-request'},{outcome:'pending'},{outcome:'failed'},{outcome:'ok'},{extra:true}])('E06 pending/failed or mismatched receipt is unconfirmed %j',patch=>expect(call('isModelConsumerInstallConfirmed',request,{...receipt,...patch},now)).toBe(false));
 it.each(['2026-10-09T06:20:30Z','2026-10-09T06:19:00Z','invalid'])('E07 readback must be fresh %s',time=>expect(call('isModelConsumerInstallConfirmed',request,receipt,new Date(time))).toBe(false));
 it.each([{settings:null},{configVersion:null},{requestId:null},{sourceVersion:' '},{validUntil:'2026-10-09T06:20:00Z'},{extra:true}])('E08 installed state has complete evidence %j',patch=>expect(schema('ModelConsumerRuntimeStateSchema').safeParse({...state,...patch}).success).toBe(false));
 it.each(['identity','scope','slotId','sourceVersion','observedAt','validUntil','status','configVersion','requestId','settings','reason','embedding'])('E15 observed state requires %s',key=>{const input={...state};Reflect.deleteProperty(input,key);expect(schema('ModelConsumerRuntimeStateSchema').safeParse(input).success).toBe(false);});
 it.each([{requestId:'other-request'}, {outcome:'pending'}, {outcome:'failed'}])('E16 receipt schema alone rejects conflicting completion %j',patch=>expect(schema('ModelConsumerInstallReceiptSchema').safeParse({...receipt,...patch}).success).toBe(false));
 it('E17 readback schema rejects wrong consumer independently of the request',()=>{expect(schema('ModelConsumerRuntimeStateSchema').safeParse({...state,settings:{...settings,capability:'memory'}}).success).toBe(false);});
 it('E18 previous embedding active is not target installed while rebuilding',()=>{const previous={...descriptor,modelId:'synthetic-old'};const emb={...settings,capability:'memory',function:'embedding',requirements:{tools:false,stream:false,structuredOutput:false},descriptor:previous,embeddingDimensions:1536};const input={...state,slotId:'memory_embedding',settings:emb,embedding:{state:'running',previous,active:previous,target:descriptor,progress:{completed:1,total:2},reason:null}};expect(schema('ModelConsumerRuntimeStateSchema').safeParse(input).success).toBe(false);});
 it('E09 unknown state stays unknown with sanitized reason',()=>{const input={...state,status:'unknown',configVersion:null,requestId:null,settings:null,reason:'Synthetic service not observed'};expect(schema('ModelConsumerRuntimeStateSchema').parse(input)).toEqual(input);expect(schema('ModelConsumerRuntimeStateSchema').safeParse({...input,reason:null}).success).toBe(false);expect(call('isModelConsumerInstallConfirmed',request,{...receipt,state:input},now)).toBe(false);});
 it('E10 shared scope cannot make another agent installed',()=>{const input={...receipt,state:{...state,scope:{...scope,agentId:'other'}}};expect(schema('ModelConsumerInstallReceiptSchema').safeParse(input).success).toBe(false);});
 it('E11 embedding readback stays previous until rebuild completes',()=>{const emb={...settings,capability:'memory',function:'embedding',requirements:{tools:false,stream:false,structuredOutput:false},embeddingDimensions:1536};const command={...request,slotId:'memory_embedding',settings:emb};const previous={...descriptor,modelId:'synthetic-old'};const rebuild={state:'running',previous,active:previous,target:descriptor,progress:{completed:1,total:2},reason:null};const observed={...state,slotId:command.slotId,settings:emb,embedding:rebuild};expect(call('isModelConsumerInstallConfirmed',command,{...receipt,state:observed},now)).toBe(false);observed.embedding={...rebuild,state:'completed',active:descriptor,progress:{completed:2,total:2}};expect(call('isModelConsumerInstallConfirmed',command,{...receipt,state:observed},now)).toBe(true);});
 it('E12 canonical transport publishes strict JSON schemas for Python and the same scope paths',()=>{const schemas=call('modelConsumerTransportJsonSchemas') as Record<string,Record<string,unknown>>;expect(schemas['install']!['additionalProperties']).toBe(false);expect(schemas['state']!['additionalProperties']).toBe(false);expect(schemas['receipt']!['additionalProperties']).toBe(false);for(const name of ['internalModelConsumerStateContract','internalModelConsumerInstallContract']){const contract=Reflect.get(HTTP,name) as {path:string,authType:string};expect(contract,name).toBeDefined();expect(contract.path).toContain('/internal/models/consumers/:slotId/');expect(contract.authType).toBe('secret');}});
 it('E14 replay identity includes the bootstrap precondition',()=>{ const fn=Reflect.get(Agent,'sameAgentCommand') as (a:unknown,b:unknown)=>boolean; const a={action:'apply-config',desiredVersion:1,requestId:request.requestId,modelBootstrap:{expectedSourceVersion:'synthetic-generation-1',expectedAbsent:true}}; expect(fn(a,a)).toBe(true);expect(fn(a,{...a,modelBootstrap:{...a.modelBootstrap,expectedSourceVersion:'changed'}})).toBe(false); const b={action:'apply-config',desiredVersion:1,requestId:request.requestId};expect(fn(a,b)).toBe(false);});
 it('E13 apply-config carries optional bootstrap absence/generation CAS without breaking old commands',()=>{const command=Reflect.get(Agent,'AgentManagementCommandSchema') as z.ZodType;const base={action:'apply-config',desiredVersion:1,requestId:request.requestId};expect(command.safeParse(base).success).toBe(true);expect(command.safeParse({...base,modelBootstrap:{expectedSourceVersion:'synthetic-generation-1',expectedAbsent:true}}).success).toBe(true);expect(command.safeParse({...base,modelBootstrap:{expectedSourceVersion:' ',expectedAbsent:true}}).success).toBe(false);expect(command.safeParse({...base,modelBootstrap:{expectedSourceVersion:'synthetic-generation-1',expectedAbsent:false}}).success).toBe(false);expect(command.safeParse({...base,action:'reload',modelBootstrap:{expectedSourceVersion:'synthetic-generation-1',expectedAbsent:true}}).success).toBe(false);});
});

describe('C5 shared runtime comparison',()=>{
 const config={schemaVersion:1,identity,configVersion:1,selections:[{slotId:request.slotId,settings}]};
 const evidence={identity,configVersion:1,requestId:request.requestId,observedAt:state.observedAt,selections:[{slotId:request.slotId,capability:settings.capability,function:settings.function,tier:'primary',descriptor}]};
 it('M01 single consumer matches one primary only',()=>{expect(call('isAgentModelRuntimeConfigurationMatching',config,evidence,now)).toBe(true);});
 it.each([{configVersion:2},{identity:{...identity,vaultAgentId:72}},{selections:[]},{selections:[{...evidence.selections[0],tier:'standard'}]},{selections:[{...evidence.selections[0],descriptor:{...descriptor,modelId:'other'}}]},{selections:[{...evidence.selections[0],capability:'other'}]},{selections:[{...evidence.selections[0],function:'tts'}]}])('M02 runtime mismatch %j stays unconfirmed',patch=>{expect(call('isAgentModelRuntimeConfigurationMatching',config,{...evidence,...patch},now)).toBe(false);});
 it('M08 extra runtime consumer does not prove the requested aggregate',()=>{const e={...evidence,selections:[...evidence.selections,{...evidence.selections[0],slotId:'extra'}]};expect(call('isAgentModelRuntimeConfigurationMatching',config,e,now)).toBe(false);});
 it('M03 failover requires both ordered descriptors',()=>{const backup={...descriptor,modelId:'synthetic-backup'};const selection={...settings,mode:'failover',primary:descriptor,fallback:backup};Reflect.deleteProperty(selection,'descriptor');const c={...config,selections:[{slotId:'stt_file',settings:{...selection,capability:'stt',function:'transcription',requirements:{tools:false,stream:false,structuredOutput:false}}}]};const e={...evidence,selections:[{slotId:'stt_file',capability:'stt',function:'transcription',tier:'primary',descriptor},{slotId:'stt_file',capability:'stt',function:'transcription',tier:'fallback',descriptor:backup}]};expect(call('isAgentModelRuntimeConfigurationMatching',c,e,now)).toBe(true);e.selections.pop();expect(call('isAgentModelRuntimeConfigurationMatching',c,e,now)).toBe(false);});
 it('M04 runtime vector dimension is part of installation evidence',()=>{const c={...config,selections:[{slotId:'memory_embedding',settings:{...settings,capability:'memory',function:'embedding',requirements:{tools:false,stream:false,structuredOutput:false},embeddingDimensions:1536}}]};const e={...evidence,selections:[{slotId:'memory_embedding',capability:'memory',function:'embedding',tier:'primary',descriptor,embeddingDimensions:1536}]};expect(call('isAgentModelRuntimeConfigurationMatching',c,e,now)).toBe(true);e.selections[0]!.embeddingDimensions=3072;expect(call('isAgentModelRuntimeConfigurationMatching',c,e,now)).toBe(false);});
 it.each(['2026-10-09T06:22:00Z','2026-10-09T06:19:00Z','invalid'])('M05 stale runtime %s remains unconfirmed',time=>expect(call('isAgentModelRuntimeConfigurationMatching',config,evidence,new Date(time))).toBe(false));
 it('M06 equivalent settings preserve mode/features/dimension/catalog authority',()=>{expect(call('sameCapabilityModelSettings',settings,{...settings,requirements:{...settings.requirements}})).toBe(true);for(const patch of [{mode:'unknown'},{catalogVersion:'other'},{requirements:{...settings.requirements,vision:true}},{descriptor:{...descriptor,modelId:'other'}}])expect(call('sameCapabilityModelSettings',settings,{...settings,...patch})).toBe(false);});
 it('M07 transport route binding rejects a path/body slot mismatch',()=>{expect(call('isModelConsumerRouteRequestMatching',{slotId:request.slotId},request)).toBe(true);expect(call('isModelConsumerRouteRequestMatching',{slotId:'security_rules'},request)).toBe(false);});
});
