import { describe, expect, it } from 'vitest';
import type { z } from 'zod';
import * as API from '../../src/model-router/index.js';
import * as HTTP from '../../src/http/index.js';

function exported(name: string): unknown { const value: unknown = Reflect.get(API, name); expect(value, name).toBeDefined(); return value; }
function schema(name: string): z.ZodType { return exported(name) as z.ZodType; }
function call(name: string, ...args: unknown[]): unknown { return (exported(name) as (...args: unknown[]) => unknown)(...args); }
const ids = ['agent_chat','agent_classifier','memory_extraction','memory_embedding','rag_embedding','rag_claim_extraction','rag_claim_validation','rag_topic_synthesis','voice_phone_live','voice_phone_delegation','voice_web_live','voice_web_delegation','voice_call_recap','elevenlabs_agent_llm','elevenlabs_agent_tts','agent_telegram_tts','scheduler_tts','briefing_tts','stt_file','glasses_stt','glasses_tts','qa_text','qa_vision','security_vision','security_rules','news_digest','news_rules','netatmo_rules','briefing_rules','research_search','research_structure','mindfulness_chat','mindfulness_tts','mindfulness_stt','lab_digest'];
const req = { tools: false, stream: false, structuredOutput: false };
const descriptor = { provider: 'openai', modelId: 'synthetic-model', protocol: 'chat-completions', adapterId: 'synthetic-adapter' };
const identity = { managementAgentId: 'synthetic-master', runtimeAgentId: 'synthetic-runtime', vaultAgentId: 71 };
const scope = { agentId: identity.runtimeAgentId, ownerId: 'synthetic-owner', tenantId: 'synthetic-tenant' };
const now = new Date('2026-10-09T06:20:00Z');
const single = { capability: 'agent-core', function: 'reasoning', catalogVersion: 'synthetic-catalog', requirements: req, mode: 'single', descriptor };
function defs(): Array<Record<string, unknown>> { return call('registeredModelConsumerDefinitions') as Array<Record<string, unknown>>; }
function source(): Record<string, unknown> { return { schemaVersion: 1, identity, scope, role: 'master', authority: 'runtime-loaded', sourceVersion: 'synthetic-generation-1', observedAt: '2026-10-09T06:19:59Z', validUntil: '2026-10-09T06:20:30Z', coverage: 'complete', selections: defs().map(d => { const requirements = d['requirements'] as typeof req; const fn = d['function']; const model = { ...descriptor, ...(fn === 'embedding' ? { protocol: 'embeddings' } : {}) }; const value:Record<string,unknown> = { ...single, capability: d['capability'], function: fn, requirements, descriptor: model, ...(fn === 'embedding' ? { embeddingDimensions: 1536 } : {}) }; if(d['routing']==='tiered'){ delete value['descriptor'];value['mode']='automatic';value['tiers']={standard:model,advanced:model,reasoning:model};value['fallback']=model; } if(d['routing']==='failover'){ delete value['descriptor'];value['mode']='failover';value['primary']=model;value['fallback']=model; } return { slotId: d['slotId'], settings: value };  }), missingSlots: [] }; }
function current(input: unknown, changes: Record<string, unknown> = {}): unknown { return call('isAgentModelBootstrapSourceCurrent', input, { identity, scope, sourceVersion: 'synthetic-generation-1', ...changes }, now); }

describe('C5 registered consumer inventory', () => {
 it('R01 covers exactly the 35 inventoried choices without model defaults', () => { const rows = defs(); expect(rows.map(d => d['slotId'])).toEqual(ids); expect(rows.map(d => (d['inventoryIds'] as string[])[0])).toEqual(ids.map((_, i) => 'C' + String(i + 1).padStart(2, '0'))); expect(call('registeredModelConsumers')).toHaveLength(35); expect(JSON.stringify(rows)).not.toContain('modelId'); });
 it.each(ids)('R02 exact canonical lookup %s remains detached', id => { const row = call('findModelConsumerDefinition', id) as Record<string, unknown>; expect(row['slotId']).toBe(id); row['scope'] = 'changed'; expect(call('findModelConsumerDefinition', id)).not.toEqual(row); expect(call('findModelConsumer', id)).toEqual(Object.fromEntries(['slotId', 'capability', 'function', 'requirements'].map(k => [k, row[k]]))); });
 it('R10 labels distinguish all 35 choices',()=>{ const labels=defs().map(row=>row['label']);expect(labels.every(label=>typeof label==='string'&&label.length>0)).toBe(true);expect(new Set(labels).size).toBe(35);});
 it('R03 registry definitions are detached including inventory IDs', () => { const rows = defs(); (rows[0]!['inventoryIds'] as string[]).push('C99'); (rows[0]!['requirements'] as typeof req).tools = false; expect(defs()[0]!['inventoryIds']).toEqual(['C01']); expect((defs()[0]!['requirements'] as typeof req).tools).toBe(true); });
 it.each(['../agent_chat', 'AGENT_CHAT', 'agent_chat ', null, {}, '__proto__'])('R04 unknown consumer grants no default %j', id => { expect(call('findModelConsumerDefinition', id)).toBeUndefined(); });
 it('R05 declares real image, structured, search and streaming requirements separately', () => { for (const id of ['qa_vision','security_vision']) expect((call('findModelConsumerDefinition',id) as {requirements:{vision:boolean}}).requirements.vision).toBe(true); expect((call('findModelConsumerDefinition','research_search') as {requirements:{webSearch:boolean}}).requirements.webSearch).toBe(true); expect((call('findModelConsumerDefinition','glasses_stt') as {requirements:typeof req}).requirements.stream).toBe(true); expect((call('findModelConsumerDefinition','security_vision') as {requirements:typeof req}).requirements.structuredOutput).toBe(true); });
 it.each(['label','scope','changeBoundary','routing','inventoryIds'])('R06 definition requires %s', key => { const row = defs()[0]!; delete row[key]; expect(schema('ModelConsumerDefinitionSchema').safeParse(row).success).toBe(false); });
 it.each([{scope:'unknown'},{changeBoundary:'immediate'},{routing:'unknown'},{inventoryIds:[]},{inventoryIds:['C99']},{inventoryIds:['C01','C01']},{extra:true}])('R07 definition rejects malformed metadata %j', patch => { expect(schema('ModelConsumerDefinitionSchema').safeParse({...defs()[0],...patch}).success).toBe(false); });
 it('R08 preserves agent_chat public requirements and old generic custom slots', () => { expect(call('findModelConsumer','agent_chat')).toEqual({slotId:'agent_chat',capability:'agent-core',function:'reasoning',requirements:{tools:true,stream:false,structuredOutput:false}}); expect(schema('ModelSlotIdSchema').parse('legacy-custom')).toBe('legacy-custom'); });
 it('R09 documents existing linked choices without aliasing slots', () => { const a = call('findModelConsumerDefinition','research_search') as Record<string,unknown>; const b = call('findModelConsumerDefinition','research_structure') as Record<string,unknown>; expect(a['linkedSelectionGroup']).toBe(b['linkedSelectionGroup']); expect(a['slotId']).not.toBe(b['slotId']); });
});

describe('C5 single and failover model settings', () => {
 it('S01 transports a single actual choice without artificial tiers', () => { expect(schema('CapabilityModelSettingsSchema').parse(single)).toEqual(single); expect(call('modelSettingsSelections',single)).toEqual([{tier:'primary',descriptor}]); });
 it('S02 retains ordered primary/fallback choices', () => { const backup={...descriptor,modelId:'synthetic-backup'}; const value={...single,mode:'failover',primary:descriptor,fallback:backup}; delete (value as Partial<typeof single>).descriptor; expect(schema('CapabilityModelSettingsSchema').parse(value)).toEqual(value); expect(call('modelSettingsSelections',value)).toEqual([{tier:'primary',descriptor},{tier:'fallback',descriptor:backup}]); });
 it.each([{descriptor:null},{descriptor:undefined},{mode:'unknown'},{tiers:{}},{extra:true}])('S03 rejects invalid single %j', patch => expect(schema('CapabilityModelSettingsSchema').safeParse({...single,...patch}).success).toBe(false));
 it.each([undefined,0,-1,1.5])('S04 embedding requires positive integer dimension %j', dimension => { expect(schema('CapabilityModelSettingsSchema').safeParse({...single,function:'embedding',embeddingDimensions:dimension}).success).toBe(false); });
 it.each(['primary','fallback'])('S08 failover requires %s',key=>{const value:Record<string,unknown>={...single,mode:'failover',primary:descriptor,fallback:descriptor};delete value['descriptor'];delete value[key];expect(schema('CapabilityModelSettingsSchema').safeParse(value).success).toBe(false);});
 it.each([{descriptor},{tiers:{}},{embeddingDimensions:1536}])('S09 failover refuses unrelated fields %j',patch=>{const value:Record<string,unknown>={...single,mode:'failover',primary:descriptor,fallback:descriptor,...patch};if(!('descriptor' in patch))delete value['descriptor'];expect(schema('CapabilityModelSettingsSchema').safeParse(value).success).toBe(false);});
 it.each(['vision','webSearch'])('S10 extra feature metadata must be boolean %s',key=>expect(schema('ModelFeaturesSchema').safeParse({...req,[key]:'true'}).success).toBe(false));
 it('S05 dimension is reserved for embedding', () => { expect(schema('CapabilityModelSettingsSchema').safeParse({...single,embeddingDimensions:1536}).success).toBe(false); expect(schema('CapabilityModelSettingsSchema').safeParse({...single,function:'embedding',embeddingDimensions:1536}).success).toBe(true); });
 it.each(['vision','webSearch'])('S06 %s requires explicit catalog support', feature => { const value={...single,requirements:{...req,[feature]:true}}; const catalog={agentId:identity.managementAgentId,version:single.catalogVersion,sourceVersion:'synthetic-catalog-source',source:'server-registry',observedAt:'2026-10-09T06:19:59Z',validUntil:'2026-10-09T06:20:30Z',state:'available',entries:[{...descriptor,function:'reasoning',label:'Synthetic',access:'available',runtimeSupport:'supported',features:{...req,tools:true}}]}; expect(call('validateCapabilityModels',value,catalog,identity.managementAgentId,now)).toEqual(['feature-unsupported']); (catalog.entries[0]!.features as Record<string,unknown>)[feature]=true; expect(call('validateCapabilityModels',value,catalog,identity.managementAgentId,now)).toEqual([]); });
 it('S07 embedding dimension must match the current catalog', () => { const value={...single,function:'embedding',embeddingDimensions:1536}; const catalog={agentId:identity.managementAgentId,version:single.catalogVersion,sourceVersion:'synthetic-catalog-source',source:'server-registry',observedAt:'2026-10-09T06:19:59Z',validUntil:'2026-10-09T06:20:30Z',state:'available',entries:[{...descriptor,function:'embedding',embeddingDimensions:3072,label:'Synthetic',access:'available',runtimeSupport:'supported',features:req}]}; expect(call('validateCapabilityModels',value,catalog,identity.managementAgentId,now)).toEqual(['embedding-dimension-mismatch']); catalog.entries[0]!.embeddingDimensions=1536; expect(call('validateCapabilityModels',value,catalog,identity.managementAgentId,now)).toEqual([]); });
});

describe('C5 read-only Master bootstrap source', () => {
 it('B01 complete source is strict and detached, with no invented saved/applied version', () => { const input=source(); const parsed=schema('AgentModelBootstrapSourceSchema').parse(input); expect(parsed).toEqual(input); expect(parsed).not.toBe(input); expect(current(input)).toBe(true); expect((parsed as Record<string,unknown>)['configVersion']).toBeUndefined(); });
 it.each(['identity','scope','role','authority','sourceVersion','observedAt','validUntil','coverage','selections','missingSlots'])('B02 source requires %s', key => { const input=source(); delete input[key]; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it.each([{role:'erede'},{authority:'catalog'},{sourceVersion:''},{sourceVersion:' '},{coverage:'unknown'},{configVersion:1},{credentials:{}},{context:{}},{extra:true},{missingSlots:['unknown']},{missingSlots:['agent_chat','agent_chat']}])('B03 rejects invalid or private metadata %j', patch => { expect(schema('AgentModelBootstrapSourceSchema').safeParse({...source(),...patch}).success).toBe(false); });
 it.each(['managementAgentId','runtimeAgentId','vaultAgentId'])('B04 complete identity requires %s', key => { const input=source(); const id={...identity}; Reflect.deleteProperty(id,key); input['identity']=id; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it.each(['ownerId','tenantId','agentId'])('B05 source scope cannot omit %s', key => { const input=source(); const target={...scope}; Reflect.deleteProperty(target,key); input['scope']=target; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it('B06 scope names the attested runtime exactly', () => { expect(schema('AgentModelBootstrapSourceSchema').safeParse({...source(),scope:{...scope,agentId:'other'}}).success).toBe(false); });
 it.each(ids)('B07 missing %s never becomes complete', id => { const input=source(); input['selections']=(input['selections'] as {slotId:string}[]).filter(s=>s.slotId!==id); expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); input['coverage']='partial'; input['missingSlots']=[id]; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(true); expect(current(input)).toBe(false); });
 it('B08 duplicate/unknown slot is rejected, coverage cannot overlap', () => { const input=source(); const rows=input['selections'] as {slotId:string}[]; rows.push(rows[0]!); expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); rows.pop(); rows[0]!.slotId='unknown'; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); expect(schema('AgentModelBootstrapSourceSchema').safeParse({...source(),coverage:'partial',missingSlots:['agent_chat']}).success).toBe(false); });
 it.each(['capability','function','requirements'])('B09 consumer rejects changed %s', key => { const input=source(); const rows=input['selections'] as {settings:Record<string,unknown>}[]; rows[0]!.settings[key]=key==='requirements'?req:'unknown'; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it.each([{sourceVersion:'synthetic-generation-2'},{identity:{...identity,vaultAgentId:72}},{identity:{...identity,managementAgentId:'other'}},{identity:{...identity,runtimeAgentId:'other'}},{scope:{...scope,ownerId:'other'}},{scope:{...scope,tenantId:'other'}},{scope:{...scope,agentId:'other'}}])('B10 fresh recheck refuses a race or scope mismatch %j', patch => { expect(current(source(),patch)).toBe(false); });
 it.each(['2026-10-09T06:20:30Z','2026-10-09T06:21:00Z','2026-10-09T06:19:00Z','invalid'])('B11 rejects expired/future/invalid clock %s', time => { expect(call('isAgentModelBootstrapSourceCurrent',source(),{identity,scope,sourceVersion:'synthetic-generation-1'},new Date(time))).toBe(false); });
 it('B12 validity end must be strictly after observation', () => { expect(schema('AgentModelBootstrapSourceSchema').safeParse({...source(),validUntil:'2026-10-09T06:19:59Z'}).success).toBe(false); });
 it('B13 unknown models stay explicit missing and never use defaults', () => { const input=source(); input['coverage']='partial'; input['selections']=[]; input['missingSlots']=ids; expect(schema('AgentModelBootstrapSourceSchema').parse(input)).toEqual(input); expect(current(input)).toBe(false); });
 it('B16 observed inactive services are explicit exclusions, active unknown stays missing', () => { const input=source(); const rows=input['selections'] as {slotId:string}[]; input['selections']=rows.filter(row=>row.slotId!=='mindfulness_stt'); input['excludedSlots']=[{slotId:'mindfulness_stt',state:'not-installed',reason:'Synthetic pipeline absent'}]; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(true); expect(current(input)).toBe(true); input['missingSlots']=['mindfulness_stt','lab_digest']; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it.each([{state:'unknown'},{reason:''},{extra:true}])('B17 exclusion is observed and strict %j', patch => { const input=source(); input['selections']=(input['selections'] as {slotId:string}[]).filter(row=>row.slotId!=='mindfulness_stt'); input['excludedSlots']=[{slotId:'mindfulness_stt',state:'not-installed',reason:'Synthetic absent',...patch}]; expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false); });
 it('B18 duplicate excluded consumer cannot erase coverage',()=>{const input=source();input['excludedSlots']=[{slotId:'agent_chat',state:'not-applicable',reason:'Synthetic'}];expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false);});
 it('B19 all excluded is not a complete loaded Master',()=>{const input=source();input['selections']=[];input['excludedSlots']=ids.map(slotId=>({slotId,state:'not-installed',reason:'Synthetic absent'}));expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false);});
 it('B20 complete cannot contain an active missing slot even with total coverage',()=>{const input=source();input['selections']=(input['selections'] as {slotId:string}[]).filter(s=>s.slotId!=='mindfulness_stt');input['missingSlots']=['mindfulness_stt','lab_digest'];expect(schema('AgentModelBootstrapSourceSchema').safeParse(input).success).toBe(false);});
 it('R12 core and audio requirements preserve the actual payload contracts',()=>{expect((call('findModelConsumerDefinition','agent_classifier') as {requirements:typeof req}).requirements).toEqual(req);for(const id of ['voice_phone_live','voice_web_live'])expect((call('findModelConsumerDefinition',id) as {requirements:typeof req}).requirements).toEqual({...req,stream:true});for(const id of ['voice_phone_delegation','voice_web_delegation'])expect((call('findModelConsumerDefinition',id) as {requirements:typeof req}).requirements).toEqual({...req,tools:true});});
 it('B14 existing state endpoint accepts additive legacy source without installed claim', () => { const contract=Reflect.get(HTTP,'internalAgentModelsStateContract') as {responseSchema:z.ZodType,path:string}; expect(contract.path).toBe('/internal/agents/:agentId/models/state'); const value={identity,versions:null,saved:null,runtime:null,bootstrapSource:source()}; expect(contract.responseSchema.parse(value)).toEqual(value); expect(schema('AgentModelsStateSchema').parse({identity,versions:null,saved:null,runtime:null})).toEqual({identity,versions:null,saved:null,runtime:null}); });
 it.each([{identity:{...identity,vaultAgentId:72}},{versions:{desired:1,applied:null,failed:null}},{runtime:{}}])('B15 source is not saved/applied and belongs to state identity %j', patch => { const value={identity,versions:null,saved:null,runtime:null,bootstrapSource:source(),...patch}; expect(schema('AgentModelsStateSchema').safeParse(value).success).toBe(false); });
});
