import { describe, expect, it } from 'vitest';
import type { z } from 'zod';
import * as router from '../../src/model-router/index.js';
const api = router as unknown as { AgentModelsOverviewSchema: z.ZodType; AgentModelsBatchRequestSchema: z.ZodType; AgentModelsBatchPreviewSchema: z.ZodType; AgentModelsBatchResultSchema: z.ZodType; ModelEmbeddingRebuildSchema: z.ZodType; validateAgentModelsBatch: (request: unknown, overview: unknown, catalogs: unknown[], now?: Date) => string[]; isAgentModelsBatchPreviewCurrent: (request: unknown, preview: unknown, overview: unknown, now?: Date) => boolean; sameAgentModelsBatchRequest: (left: unknown, right: unknown) => boolean; isAgentModelsBatchResultConsistent: (request: unknown, preview: unknown, result: unknown, now?: Date) => boolean; deriveAgentModelsBatchOutcome: (statuses: readonly string[]) => string };
const now = new Date('2026-10-07T16:30:00Z');
const identity = { managementAgentId: 'agent-42', runtimeAgentId: 'runtime-42', vaultAgentId: 42 };
const descriptor = { provider: 'openai', modelId: 'synthetic-model', protocol: 'responses', adapterId: 'synthetic-adapter' };
const settings = () => ({ capability: 'agent-core', function: 'reasoning', catalogVersion: 'catalog-1', requirements: { tools: true, stream: true, structuredOutput: false }, mode: 'pin', pin: { ...descriptor }, tiers: { standard: { ...descriptor }, advanced: { ...descriptor }, reasoning: { ...descriptor } }, fallback: { ...descriptor } });
const row = () => ({ identity: { ...identity }, ownerId: 'owner-42', slotId: 'agent_chat', capability: 'agent-core', function: 'reasoning', channelId: null, installation: 'installed', editability: 'editable', reason: null as string | null, origin: 'custom', masterAgentId: 'primary', masterConfigVersion: 2, requirements: { tools: true, stream: true, structuredOutput: false }, default: settings(), saved: settings(), applied: settings(), versions: { desired: 3, applied: 3, failed: null }, catalogVersion: 'catalog-1', cost: { state: 'unknown', reason: 'No attested price' }, embedding: null });
const overview = () => ({ version: 'overview-1', observedAt: now.toISOString(), rows: [row()] });
const request = () => ({ requestId: 'batch-request-42', previewId: 'preview-0042', overviewVersion: 'overview-1', agents: [{ identity: { ...identity }, expectedVersion: 3, changes: [{ action: 'set', slotId: 'agent_chat', settings: settings() }] }] });
const catalog = () => ({ agentId: 'agent-42', version: 'catalog-1', sourceVersion: 'source-1', source: 'provider-api', observedAt: now.toISOString(), validUntil: new Date(now.getTime() + 60_000).toISOString(), state: 'available', entries: [{ ...descriptor, function: 'reasoning', label: 'Synthetic model', access: 'available', runtimeSupport: 'supported', features: { tools: true, stream: true, structuredOutput: true } }] });
const configuration = () => ({ schemaVersion: 1, identity: { ...identity }, configVersion: 4, selections: [{ slotId: 'agent_chat', settings: settings() }] });
const preview = () => { const { previewId: _preview, ...input } = request(); return { previewId: 'preview-0042', request: input, expiresAt: new Date(now.getTime() + 60_000).toISOString(), agents: [{ identity: { ...identity }, expectedVersion: 3, next: configuration(), impact: ['One capability configuration will change'] }] }; };
const rebuild = () => ({ state: 'running', previous: { ...descriptor, modelId: 'old-embedding' }, active: { ...descriptor, modelId: 'old-embedding' }, target: { ...descriptor, modelId: 'new-embedding' }, progress: { completed: 2, total: 10 }, reason: null });
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

describe('sole editor overview and batch contract', () => {
  it('exports overview, batch preview and apply result schemas', () => { for (const key of ['AgentModelsOverviewSchema', 'AgentModelsBatchRequestSchema', 'AgentModelsBatchPreviewSchema', 'AgentModelsBatchResultSchema', 'ModelEmbeddingRebuildSchema', 'validateAgentModelsBatch', 'isAgentModelsBatchPreviewCurrent']) expect(api[key as keyof typeof api]).toBeDefined(); });
  it('supports stable per-agent slots, source, saved/applied/default values and unknown cost', () => { expect(api.AgentModelsOverviewSchema.safeParse(overview()).success).toBe(true); });
  it('rejects duplicate rows and inconsistent identity mappings', () => { const value = overview(); value.rows.push(row()); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); value.rows[1]!.slotId = 'news_digest'; value.rows[1]!.identity.runtimeAgentId = 'other'; expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
  it.each(['capability', 'function'])('binds %s in saved/default/applied selections to the row', key => { for (const field of ['default', 'saved', 'applied']) { const value = overview(); Object.assign(value.rows[0]![field as 'saved'], { [key]: key === 'function' ? 'tts' : 'cap-news' }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); } });
  it('requires a reason for a readonly slot and a master identity when following Master', () => { const value = overview(); value.rows[0]!.editability = 'readonly'; expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); value.rows[0]!.reason = 'Role forbids editing'; expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(true); const master = overview(); master.rows[0]!.origin = 'master'; Object.assign(master.rows[0]!, { masterAgentId: null }); expect(api.AgentModelsOverviewSchema.safeParse(master).success).toBe(false); });
  it('requires a unit, source and observation for known costs', () => { const value = overview(); Object.assign(value.rows[0]!, { cost: { state: 'known', currency: 'USD', rates: [{ unit: 'million-input-tokens', amount: 0.5 }], source: 'Synthetic provider documentation', observedAt: now.toISOString() } }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(true); const cost = value.rows[0]!.cost as unknown as { source?: string }; delete cost.source; expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
  it.each([-1, Infinity])('rejects invalid cost %s', amount => { const value = overview(); Object.assign(value.rows[0]!, { cost: { state: 'known', currency: 'USD', rates: [{ unit: 'million-input-tokens', amount }], source: 'Synthetic', observedAt: now.toISOString() } }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
  it('rejects secrets and internal URLs as DTO fields', () => { expect(api.AgentModelsOverviewSchema.safeParse({ ...overview(), token: 'synthetic' }).success).toBe(false); const value = overview(); Object.assign(value.rows[0]!, { baseUrl: 'synthetic' }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); expect(api.AgentModelsBatchRequestSchema.safeParse({ ...request(), token: 'synthetic' }).success).toBe(false); });
  it('accepts preview-bound multi-agent submissions with existing version/request IDs', () => { expect(api.AgentModelsBatchRequestSchema.safeParse(request()).success).toBe(true); });
  it('rejects duplicate batch agents and duplicate slot changes', () => { const value = request(); value.agents.push(value.agents[0]!); expect(api.AgentModelsBatchRequestSchema.safeParse(value).success).toBe(false); const changes = request(); changes.agents[0]!.changes.push(changes.agents[0]!.changes[0]!); expect(api.AgentModelsBatchRequestSchema.safeParse(changes).success).toBe(false); });
  it('rejects empty agents or changes', () => { expect(api.AgentModelsBatchRequestSchema.safeParse({ ...request(), agents: [] }).success).toBe(false); const value = request(); value.agents[0]!.changes = []; expect(api.AgentModelsBatchRequestSchema.safeParse(value).success).toBe(false); });
  it('validates a batch against producer overview and fresh catalog', () => { expect(api.validateAgentModelsBatch(request(), overview(), [catalog()], now)).toEqual([]); });
  it.each(['request', 'overview'])('rejects malformed %s', key => { expect(api.validateAgentModelsBatch(key === 'request' ? {} : request(), key === 'overview' ? {} : overview(), [catalog()], now)).toContain(key === 'request' ? 'invalid-request' : 'invalid-overview'); });
  it('rejects stale overview version', () => { expect(api.validateAgentModelsBatch({ ...request(), overviewVersion: 'old' }, overview(), [catalog()], now)).toContain('overview-version-mismatch'); });
  it('rejects unregistered slots, identities and CAS conflicts', () => { const missing = request(); missing.agents[0]!.changes[0]!.slotId = 'missing'; expect(api.validateAgentModelsBatch(missing, overview(), [catalog()], now)).toContain('slot-not-found'); const other = request(); other.agents[0]!.identity.runtimeAgentId = 'other'; expect(api.validateAgentModelsBatch(other, overview(), [catalog()], now)).toContain('identity-mismatch'); const stale = request(); stale.agents[0]!.expectedVersion = 2; expect(api.validateAgentModelsBatch(stale, overview(), [catalog()], now)).toContain('version-conflict'); });
  it('refuses unknown versions, absent capability and readonly slots', () => { const unknown = overview(); Object.assign(unknown.rows[0]!, { versions: null, applied: null }); expect(api.validateAgentModelsBatch(request(), unknown, [catalog()], now)).toContain('version-unknown'); const absent = overview(); absent.rows[0]!.installation = 'absent'; expect(api.validateAgentModelsBatch(request(), absent, [catalog()], now)).toContain('slot-unavailable'); const readonly = overview(); Object.assign(readonly.rows[0]!, { editability: 'readonly', reason: 'Role forbids editing' }); expect(api.validateAgentModelsBatch(request(), readonly, [catalog()], now)).toContain('slot-readonly'); });
  it.each(['capability', 'function'])('rejects a fabricated %s choice', key => { const value = request(); Object.assign(value.agents[0]!.changes[0]!.settings, { [key]: key === 'function' ? 'tts' : 'cap-news' }); expect(api.validateAgentModelsBatch(value, overview(), [catalog()], now)).toContain('slot-function-mismatch'); });
  it('refuses missing, stale or unavailable catalog evidence', () => { expect(api.validateAgentModelsBatch(request(), overview(), [], now)).toContain('catalog-unavailable'); expect(api.validateAgentModelsBatch(request(), overview(), [catalog()], new Date(now.getTime() + 60_000))).toContain('model-selection-invalid'); });
  it('does not let the caller weaken the capability requirements', () => { const value = request(); value.agents[0]!.changes[0]!.settings.requirements.tools = false; expect(api.validateAgentModelsBatch(value, overview(), [catalog()], now)).toContain('requirements-mismatch'); });
  it('allows reset only with an attested Master default and validates its catalog', () => { const value = request(); Object.assign(value.agents[0]!, { changes: [{ action: 'reset-master', slotId: 'agent_chat' }] }); expect(api.validateAgentModelsBatch(value, overview(), [catalog()], now)).toEqual([]); const noMaster = overview(); Object.assign(noMaster.rows[0]!, { masterAgentId: null, default: null }); expect(api.validateAgentModelsBatch(value, noMaster, [catalog()], now)).toContain('master-default-unavailable'); });
});

describe('versioned preview binding', () => {
  it('accepts an exact unexpired preview', () => { expect(api.AgentModelsBatchPreviewSchema.safeParse(preview()).success).toBe(true); expect(api.isAgentModelsBatchPreviewCurrent(request(), preview(), overview(), now)).toBe(true); });
  it.each(['previewId', 'requestId', 'overviewVersion'])('rejects changed %s after preview', key => { expect(api.isAgentModelsBatchPreviewCurrent({ ...request(), [key]: 'changed-version' }, preview(), overview(), now)).toBe(false); });
  it('rejects stale preview exactly at expiration and an invalid clock', () => { expect(api.isAgentModelsBatchPreviewCurrent(request(), preview(), overview(), new Date(preview().expiresAt))).toBe(false); expect(api.isAgentModelsBatchPreviewCurrent(request(), preview(), overview(), new Date(NaN))).toBe(false); });
  it('rejects an overview changed since preview', () => { expect(api.isAgentModelsBatchPreviewCurrent(request(), preview(), { ...overview(), version: 'new-version' }, now)).toBe(false); });
  it('rejects modified CAS, identity or settings after preview', () => { const value = request(); value.agents[0]!.expectedVersion = 2; expect(api.isAgentModelsBatchPreviewCurrent(value, preview(), overview(), now)).toBe(false); const other = request(); other.agents[0]!.identity.vaultAgentId = 43; expect(api.isAgentModelsBatchPreviewCurrent(other, preview(), overview(), now)).toBe(false); const change = request(); change.agents[0]!.changes[0]!.settings.catalogVersion = 'different'; expect(api.isAgentModelsBatchPreviewCurrent(change, preview(), overview(), now)).toBe(false); });
  it('requires next version to increment the expected one', () => { const value = preview(); value.agents[0]!.next.configVersion = 5; expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });
  it('requires preview agent/config identity and exact requested agent set', () => { const value = preview(); value.agents[0]!.next.identity.runtimeAgentId = 'other'; expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); const missing = preview(); missing.agents = []; expect(api.AgentModelsBatchPreviewSchema.safeParse(missing).success).toBe(false); });
  it('requires previewed set selections to match the proposed changes', () => { const value = preview(); value.agents[0]!.next.selections[0]!.settings.catalogVersion = 'other'; expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });
});

describe('embedding rebuild keeps the current model until completion', () => {
  it('reports denominator-based progress and the current/target models separately', () => { expect(api.ModelEmbeddingRebuildSchema.safeParse(rebuild()).success).toBe(true); });
  it('requires progress inside its denominator', () => { const value = rebuild(); value.progress.completed = 11; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
  it.each([0, -1, 1.5])('rejects invalid total %s', total => { const value = rebuild(); value.progress.total = total; value.progress.completed = total === 1.5 ? 1 : 0; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
  it('requires completed rebuild progress to be complete and the target active', () => { const value = rebuild(); value.state = 'completed'; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); value.progress.completed = value.progress.total; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); value.active = value.target; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(true); });
  it.each(['pending', 'running', 'failed'])('does not switch the model during %s rebuild', state => { const value = rebuild(); value.state = state; if (state === 'failed') Object.assign(value, { reason: 'Synthetic rebuild failure' }); value.active = value.target; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
  it('requires a failure reason exactly on failure', () => { const value = rebuild(); value.state = 'failed'; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); Object.assign(value, { reason: 'Synthetic failure' }); expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(true); Object.assign(value, { state: 'running' }); expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
});

it.each([[['applied', 'applied'], 'applied'], [['applied', 'failed'], 'partial'], [['pending', 'failed'], 'pending'], [['failed', 'conflict'], 'failed'], [[], 'failed']])('derives batch outcome from every agent: %j', (statuses, expected) => { expect(api.deriveAgentModelsBatchOutcome(statuses as string[])).toBe(expected); });

it('rejects inconsistent versions across the same agent slots', () => { const value = overview(); value.rows.push(row()); value.rows[1]!.slotId = 'news_digest'; value.rows[1]!.versions.desired = 4; expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it('rejects ambiguous management/runtime aliases across agents', () => { const value = overview(); const other = row(); other.identity.managementAgentId = 'runtime-42'; other.identity.runtimeAgentId = 'runtime-other'; value.rows.push(other); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it('requires an applied version for an applied selection', () => { const value = overview(); Object.assign(value.rows[0]!.versions, { applied: null }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it('requires Master version and default for reset', () => { const input = request(); Object.assign(input.agents[0]!, { changes: [{ action: 'reset-master', slotId: 'agent_chat' }] }); const value = overview(); Object.assign(value.rows[0]!, { masterConfigVersion: null }); expect(api.validateAgentModelsBatch(input, value, [catalog()], now)).toContain('master-default-unavailable'); });
it('rejects duplicate agent catalogs and changed catalog reference', () => { expect(api.validateAgentModelsBatch(request(), overview(), [catalog(), catalog()], now)).toContain('catalog-unavailable'); const value = overview(); value.rows[0]!.catalogVersion = 'old'; expect(api.validateAgentModelsBatch(request(), value, [catalog()], now)).toContain('catalog-unavailable'); });
it('rejects rebuild metadata on another function', () => { const value = overview(); Object.assign(value.rows[0]!, { embedding: rebuild() }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });

const appliedBatch = () => ({ requestId: 'batch-request-42', previewId: 'preview-0042', outcome: 'applied', results: [{ configuration: configuration(), savedVersion: 4, status: 'applied', reason: null, result: { ok: true, agentId: 'agent-42', identity: { ...identity }, action: 'apply-config', requestId: 'batch-request-42', replayed: false, outcome: 'ok', requestedVersion: 4, versions: { desired: 4, applied: 4, failed: null }, results: [{ target: { kind: 'runtime', targetId: 'runtime-42' }, outcome: 'ok' }], completedAt: now.toISOString() }, runtime: { identity: { ...identity }, configVersion: 4, requestId: 'batch-request-42', observedAt: now.toISOString(), selections: ['standard', 'advanced', 'reasoning', 'fallback'].map(tier => ({ slotId: 'agent_chat', capability: 'agent-core', function: 'reasoning', tier, descriptor: { ...descriptor } })) } }] });
it('accepts per-agent applied evidence and checks exact submitted preview', () => { expect(api.AgentModelsBatchResultSchema.safeParse(appliedBatch()).success).toBe(true); expect(api.isAgentModelsBatchResultConsistent(request(), preview(), appliedBatch(), now)).toBe(true); });
it('does not claim applied without runtime evidence', () => { const value = appliedBatch(); Object.assign(value.results[0]!, { runtime: null }); expect(api.AgentModelsBatchResultSchema.safeParse(value).success).toBe(false); });
it('derives result outcome and rejects unreported or duplicate agents', () => { const value = appliedBatch(); value.outcome = 'partial'; expect(api.AgentModelsBatchResultSchema.safeParse(value).success).toBe(false); const duplicate = appliedBatch(); duplicate.results.push(duplicate.results[0]!); expect(api.AgentModelsBatchResultSchema.safeParse(duplicate).success).toBe(false); });
it('requires a reason exactly when not applied', () => { const value = appliedBatch(); Object.assign(value.results[0]!, { reason: { code: 'unknown' } }); expect(api.AgentModelsBatchResultSchema.safeParse(value).success).toBe(false); const pending = appliedBatch(); pending.outcome = 'pending'; pending.results[0]!.status = 'pending'; Object.assign(pending.results[0]!, { runtime: null, result: null }); expect(api.AgentModelsBatchResultSchema.safeParse(pending).success).toBe(false); Object.assign(pending.results[0]!, { reason: { code: 'in-progress' } }); expect(api.AgentModelsBatchResultSchema.safeParse(pending).success).toBe(true); });
it.each(['requestId', 'previewId'])('rejects a response for another %s', key => { const value = appliedBatch(); Object.assign(value, { [key]: 'other-request' }); expect(api.isAgentModelsBatchResultConsistent(request(), preview(), value, now)).toBe(false); });
it('rejects stale applied result evidence', () => { expect(api.isAgentModelsBatchResultConsistent(request(), preview(), appliedBatch(), new Date(now.getTime() + 60_001))).toBe(false); });
it('rejects modified proposed configuration after submit', () => { const value = appliedBatch(); value.results[0]!.configuration.selections[0]!.settings.catalogVersion = 'other'; expect(api.isAgentModelsBatchResultConsistent(request(), preview(), value, now)).toBe(false); });
it('does not hide partial apply with another pending agent', () => { const value = appliedBatch(); const other = clone(value.results[0]!); other.configuration.identity.managementAgentId = 'agent-other'; other.configuration.identity.runtimeAgentId = 'runtime-other'; other.configuration.identity.vaultAgentId = 43; Object.assign(other, { status: 'pending', result: null, runtime: null, reason: { code: 'timeout' } }); value.results.push(other); value.outcome = 'partial'; expect(api.AgentModelsBatchResultSchema.safeParse(value).success).toBe(true); expect(api.isAgentModelsBatchResultConsistent(request(), preview(), value, now)).toBe(false); });

it('validates the preview intent before a preview id exists', () => { const { previewId: _id, ...input } = request(); expect(api.validateAgentModelsBatch(input, overview(), [catalog()], now)).toEqual([]); });

it.each(['tools', 'stream', 'structuredOutput'])('refuses weakened consumer requirement %s', key => { const input = request(); Object.assign(input.agents[0]!.changes[0]!.settings.requirements, { [key]: !input.agents[0]!.changes[0]!.settings.requirements[key as 'tools'] }); expect(api.validateAgentModelsBatch(input, overview(), [catalog()], now)).toContain('requirements-mismatch'); });
it.each(['installation', 'editability', 'origin'])('rejects unknown overview semantics %s', key => { const value = overview(); Object.assign(value.rows[0]!, { [key]: 'invented' }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it.each(['currency', 'unit', 'source', 'observedAt', 'rates'])('rejects invalid known cost metadata %s', key => { const cost = { state: 'known', currency: 'USD', rates: [{ unit: 'million-input-tokens', amount: 1 }], source: 'Synthetic', observedAt: now.toISOString() }; if (key === 'unit') cost.rates[0]!.unit = 'invented'; else Object.assign(cost, { [key]: key === 'rates' ? [] : key === 'source' ? '' : 'invalid' }); const value = overview(); Object.assign(value.rows[0]!, { cost }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it('rejects extra cost, rate, rebuild and progress metadata', () => { for (const cost of [{ state: 'unknown', reason: 'Synthetic', token: 'synthetic' }, { state: 'known', currency: 'USD', rates: [{ unit: 'call', amount: 0, token: 'synthetic' }], source: 'Synthetic', observedAt: now.toISOString() }, { state: 'known', currency: 'USD', rates: [{ unit: 'call', amount: 0 }], source: 'Synthetic', observedAt: now.toISOString(), token: 'synthetic' }]) { const value = overview(); Object.assign(value.rows[0]!, { cost }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); } expect(api.ModelEmbeddingRebuildSchema.safeParse({ ...rebuild(), token: 'synthetic' }).success).toBe(false); expect(api.ModelEmbeddingRebuildSchema.safeParse({ ...rebuild(), progress: { completed: 2, total: 10, token: 'synthetic' } }).success).toBe(false); });
it.each([-1, 1.5])('rejects invalid completed progress %s', completed => { const value = rebuild(); value.progress.completed = completed; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
it('rejects unknown rebuild status and extra batch/change/preview fields', () => { expect(api.ModelEmbeddingRebuildSchema.safeParse({ ...rebuild(), state: 'invented' }).success).toBe(false); const value = request(); Object.assign(value.agents[0]!, { token: 'synthetic' }); expect(api.AgentModelsBatchRequestSchema.safeParse(value).success).toBe(false); const change = request(); Object.assign(change.agents[0]!.changes[0]!, { baseUrl: 'synthetic' }); expect(api.AgentModelsBatchRequestSchema.safeParse(change).success).toBe(false); expect(api.AgentModelsBatchPreviewSchema.safeParse({ ...preview(), token: 'synthetic' }).success).toBe(false); const next = preview(); Object.assign(next.agents[0]!, { baseUrl: 'synthetic' }); expect(api.AgentModelsBatchPreviewSchema.safeParse(next).success).toBe(false); });
it('rejects a preview expectedVersion different from the request', () => { const value = preview(); value.agents[0]!.expectedVersion = 2; value.agents[0]!.next.configVersion = 3; expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });
it('rejects a missing changed slot in the preview', () => { const value = preview(); value.agents[0]!.next.selections[0]!.slotId = 'unrelated'; expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });
it('rejects malformed preview inputs', () => { expect(api.isAgentModelsBatchPreviewCurrent({}, preview(), overview(), now)).toBe(false); expect(api.isAgentModelsBatchPreviewCurrent(request(), {}, overview(), now)).toBe(false); expect(api.isAgentModelsBatchPreviewCurrent(request(), preview(), {}, now)).toBe(false); });
it('rejects malformed processed batch inputs', () => { expect(api.isAgentModelsBatchResultConsistent({}, preview(), appliedBatch(), now)).toBe(false); expect(api.isAgentModelsBatchResultConsistent(request(), {}, appliedBatch(), now)).toBe(false); expect(api.isAgentModelsBatchResultConsistent(request(), preview(), {}, now)).toBe(false); });

it('does not mark an active target rebuild complete before progress is complete', () => { const value = rebuild(); value.state = 'completed'; value.active = value.target; expect(api.ModelEmbeddingRebuildSchema.safeParse(value).success).toBe(false); });
it('requires all requested preview agents even when the preview has one valid agent', () => { const value = preview(); const other = clone(value.request.agents[0]!); other.identity.managementAgentId = 'agent-other'; other.identity.runtimeAgentId = 'runtime-other'; other.identity.vaultAgentId = 43; value.request.agents.push(other); expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });
it('rejects duplicate preview agents when the requested count still matches', () => { const value = preview(); const other = clone(value.request.agents[0]!); other.identity.managementAgentId = 'agent-other'; other.identity.runtimeAgentId = 'runtime-other'; other.identity.vaultAgentId = 43; value.request.agents.push(other); value.agents.push(clone(value.agents[0]!)); expect(api.AgentModelsBatchPreviewSchema.safeParse(value).success).toBe(false); });

it('does not accept pending progress for another request', () => { const value = appliedBatch(); value.requestId = 'different-request'; value.outcome = 'pending'; value.results[0]!.status = 'pending'; Object.assign(value.results[0]!, { result: null, runtime: null, reason: { code: 'in-progress' } }); expect(api.isAgentModelsBatchResultConsistent(request(), preview(), value, now)).toBe(false); });

it('replays only an identical preview-bound request before CAS', () => { expect(api.sameAgentModelsBatchRequest(request(), clone(request()))).toBe(true); expect(api.sameAgentModelsBatchRequest({}, request())).toBe(false); expect(api.sameAgentModelsBatchRequest(request(), {})).toBe(false); });
it.each(['requestId', 'previewId', 'overviewVersion'])('rejects replay with changed %s', key => { expect(api.sameAgentModelsBatchRequest(request(), { ...request(), [key]: 'other-request' })).toBe(false); });
it('rejects replay with changed configuration or expected version', () => { const value = request(); value.agents[0]!.expectedVersion = 2; expect(api.sameAgentModelsBatchRequest(request(), value)).toBe(false); const input = request(); input.agents[0]!.changes[0]!.settings.catalogVersion = 'other'; expect(api.sameAgentModelsBatchRequest(request(), input)).toBe(false); });
it('compares replay agent/slot sets without treating order as another write', () => { const value = request(); const other = clone(value.agents[0]!); other.identity.managementAgentId = 'agent-other'; other.identity.runtimeAgentId = 'runtime-other'; other.identity.vaultAgentId = 43; value.agents.push(other); value.agents[0]!.changes.push({ ...clone(value.agents[0]!.changes[0]!), slotId: 'news_digest' }); const reordered = clone(value); reordered.agents.reverse(); reordered.agents.find(agent => agent.identity.managementAgentId === 'agent-42')!.changes.reverse(); expect(api.sameAgentModelsBatchRequest(value, reordered)).toBe(true); });

it('bounds submitted agents and changed slots independently', () => { const agents = request(); agents.agents = Array.from({ length: 65 }, (_, i) => ({ ...clone(agents.agents[0]!), identity: { managementAgentId: 'agent-' + i, runtimeAgentId: 'runtime-' + i, vaultAgentId: i + 1 } })); expect(api.AgentModelsBatchRequestSchema.safeParse(agents).success).toBe(false); const changes = request(); changes.agents[0]!.changes = Array.from({ length: 65 }, (_, i) => ({ ...clone(changes.agents[0]!.changes[0]!), slotId: 'slot-' + i })); expect(api.AgentModelsBatchRequestSchema.safeParse(changes).success).toBe(false); });
it('bounds overview rows without relying on duplicate identities or slots', () => { const value = overview(); value.rows = Array.from({ length: 2049 }, (_, i) => ({ ...row(), slotId: 'slot-' + i })); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });

it('rejects inconsistent owner metadata across an agent slots', () => { const value = overview(); value.rows.push({ ...row(), slotId: 'news_digest', ownerId: 'other-owner' }); expect(api.AgentModelsOverviewSchema.safeParse(value).success).toBe(false); });
it('distinguishes proposed, saved and applied versions in each batch result', () => { const missing = appliedBatch(); Object.assign(missing.results[0]!, { savedVersion: null }); expect(api.AgentModelsBatchResultSchema.safeParse(missing).success).toBe(false); const wrong = appliedBatch(); wrong.results[0]!.savedVersion = 3; expect(api.AgentModelsBatchResultSchema.safeParse(wrong).success).toBe(false); const conflict = appliedBatch(); conflict.outcome = 'failed'; Object.assign(conflict.results[0]!, { status: 'conflict', result: null, runtime: null, reason: { code: 'validation-failed' } }); expect(api.AgentModelsBatchResultSchema.safeParse(conflict).success).toBe(false); Object.assign(conflict.results[0]!, { savedVersion: null }); expect(api.AgentModelsBatchResultSchema.safeParse(conflict).success).toBe(true); });

it('binds reset-Master preview selections to the current server default', () => { const input = request(); Object.assign(input.agents[0]!, { changes: [{ action: 'reset-master', slotId: 'agent_chat' }] }); const proposed = preview(); Object.assign(proposed.request.agents[0]!, { changes: [{ action: 'reset-master', slotId: 'agent_chat' }] }); expect(api.isAgentModelsBatchPreviewCurrent(input, proposed, overview(), now)).toBe(true); proposed.agents[0]!.next.selections[0]!.settings.catalogVersion = 'other-default'; expect(api.isAgentModelsBatchPreviewCurrent(input, proposed, overview(), now)).toBe(false); });

it('checks the final configuration as a slot set rather than serialization order', () => { const submitted = request(); const proposed = preview(); const response = appliedBatch(); const extra = { slotId: 'news_digest', settings: settings() }; proposed.agents[0]!.next.selections.push(clone(extra)); response.results[0]!.configuration.selections.push(clone(extra)); const copied = response.results[0]!.runtime.selections.map(entry => ({ ...clone(entry), slotId: 'news_digest' })); response.results[0]!.runtime.selections.push(...copied); response.results[0]!.configuration.selections.reverse(); expect(api.isAgentModelsBatchResultConsistent(submitted, proposed, response, now)).toBe(true); });
