import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const root=process.argv[2];
const require=createRequire(`${root}/package.json`);
const now=new Date('2026-10-09T13:00:00Z');
const identity={managementAgentId:'agent-a',runtimeAgentId:'runtime-a',vaultAgentId:41};
const other={managementAgentId:'agent-b',runtimeAgentId:'runtime-b',vaultAgentId:42};
const descriptor={provider:'openai',modelId:'synthetic-model',protocol:'responses',adapterId:'synthetic-adapter'};
const requirements={tools:true,stream:true,structuredOutput:false};
const settings={capability:'agent-core',function:'reasoning',catalogVersion:'catalog-1',requirements,mode:'pin',pin:descriptor,tiers:{standard:descriptor,advanced:descriptor,reasoning:descriptor},fallback:descriptor};
const row={identity,ownerId:'owner-a',slotId:'agent_chat',capability:'agent-core',function:'reasoning',channelId:null,installation:'installed',editability:'editable',reason:null,origin:'custom',masterAgentId:null,masterConfigVersion:null,requirements,default:null,saved:settings,applied:null,versions:{desired:3,applied:null,failed:null},catalogVersion:'catalog-1',cost:{state:'unknown',reason:'No observed price'},embedding:null};
const coverage={identity,ownerId:'owner-a',status:'complete',missingSlots:[],reason:null};
const overview={version:'overview-1',observedAt:now.toISOString(),rows:[row],coverage:[coverage]};
const request={requestId:'request-0001',overviewVersion:'overview-1',agents:[{identity,expectedVersion:3,changes:[{action:'set',slotId:'agent_chat',settings}]}]};
const catalog={agentId:'agent-a',version:'catalog-1',sourceVersion:'source-1',source:'provider-api',observedAt:now.toISOString(),validUntil:'2026-10-09T13:01:00Z',state:'available',entries:[{...descriptor,function:'reasoning',label:'Synthetic',access:'available',runtimeSupport:'supported',features:{tools:true,stream:true,structuredOutput:true}}]};
let assertions=0;
for(const format of ['esm','cjs']){
 const load=specifier=>format==='cjs'?require(specifier):import(pathToFileURL(require.resolve(specifier)).href.replace(/\.cjs$/,'.js'));
 const models=await load('@x9-forge/contracts/model-router');
 const http=await load('@x9-forge/contracts/http');
 const auth=await load('@x9-forge/contracts/auth');
 const ok=(value,expected=true)=>{assert.equal(value,expected);assertions++};
 ok(models.AgentModelsOverviewSchema.safeParse(overview).success);
 const {coverage:_coverage,...legacy}=overview;
 assert.equal(models.AgentModelsOverviewSchema.parse(legacy).coverage,undefined);assertions++;
 ok(models.AgentModelsOverviewSchema.safeParse({...overview,rows:[]}).success);
 ok(models.AgentModelsOverviewSchema.safeParse({...overview,rows:[{...row,origin:'unknown',editability:'readonly',reason:'Provenance unavailable'}]}).success);
 ok(models.AgentModelsOverviewSchema.safeParse({...overview,rows:[{...row,origin:'unknown'}]}).success,false);
 ok(models.AgentModelsOverviewSchema.safeParse({...overview,coverage:[{...coverage,identity:{...identity,runtimeAgentId:'different'}}]}).success,false);
 ok(models.AgentModelsOverviewSchema.safeParse({...overview,rows:[],coverage:[coverage,{...coverage,identity:{...other,vaultAgentId:41}}]}).success,false);
 ok(http.isAgentModelsOverviewWithinAccess({...overview,rows:[],coverage:[{...coverage,ownerId:'owner-b'}]},{role:'owner',ownerId:'owner-a'}),false);
 const partial={...coverage,status:'partial',reason:'Incomplete'};
 assert.deepEqual(models.validateAgentModelsBatch(request,{...overview,coverage:[coverage,{...partial,identity:other}]},[catalog],now),[]);assertions++;
 ok(models.validateAgentModelsBatch(request,{...overview,coverage:[partial]},[catalog],now).includes('slot-unavailable'));
 ok(http.internalAgentModelSourceObservationContract.method,'GET');
 ok(http.internalAgentModelSourceObservationContract.authHeader,auth.INTERNAL_SECRET_HEADER);
 ok(http.internalAgentModelSourceObservationContract.responseSchema,models.AgentModelSourceObservationSchema);
 ok(http.agentModelSourceObservationPath('agent-a'),'/internal/agents/agent-a/models/local-source');
 console.log(format,'14 assertions passed');
}
console.log(JSON.stringify({formats:2,assertions,root}));
