import {expect,it} from 'vitest';
import * as H from '../../src/http/index.js';
import * as C from '../../src/capability/index.js';
const definitions=[['elevenLabsWebSnapshotContract','GET','', 'ElevenLabsWebAdmissionSnapshotSchema',null],['elevenLabsWebPolicyContract','PUT','/policy','ElevenLabsWebPolicyResultSchema','ElevenLabsWebPolicyChangeSchema'],['elevenLabsWebCatalogContract','GET','/catalog','ElevenLabsWebCatalogSchema',null],['elevenLabsWebSessionContract','POST','/session','ElevenLabsWebSessionResultSchema','ElevenLabsWebSessionRequestSchema']] as const;
it.each(definitions)('exports secret-auth canonical %s', (name,method,suffix,response,body)=>{const endpoint=Reflect.get(H,name);expect(endpoint).toBeDefined();expect(endpoint).toMatchObject({method,path:'/internal/capability/agents/:agentId/elevenlabs/web'+suffix,authType:'secret',responseSchema:Reflect.get(C,response)});if(body!==null)expect(endpoint).toHaveProperty('bodySchema',Reflect.get(C,body));});
it.each(['arbitrary-heir','primary-agent','sibling-b'])('builds canonical scoped path %s',agentId=>{expect(Reflect.get(H,'capElevenLabsWebPath')).toBeTypeOf('function');expect(Reflect.get(H,'capElevenLabsWebSessionPath')).toBeTypeOf('function');expect(Reflect.get(H,'capElevenLabsWebPath')(agentId)).toBe('/internal/capability/agents/'+agentId+'/elevenlabs/web');expect(Reflect.get(H,'capElevenLabsWebSessionPath')(agentId)).toBe('/internal/capability/agents/'+agentId+'/elevenlabs/web/session');});
it.each(['../other','UPPER','agent/other',''])('rejects invalid scoped path %s',agentId=>{expect(()=>Reflect.get(H,'capElevenLabsWebPath')(agentId)).toThrow();expect(()=>Reflect.get(H,'capElevenLabsWebSessionPath')(agentId)).toThrow();});
it('does not expose a session principal as a public browser command',()=>{expect(Reflect.get(H,'elevenLabsWebSessionContract')).toBeDefined();expect(Reflect.get(H,'elevenLabsWebSessionContract')).toHaveProperty('authType','secret');expect(Reflect.get(H,'elevenLabsWebSessionContract')).not.toHaveProperty('authentication','none');});

it('exports the canonical public speaking route for Forge and X9',()=>expect(Reflect.get(H,'ELEVENLABS_WEB_PUBLIC_PAGE_PATH')).toBe('/parla/:linkId'));
it.each(['synthetic-link','arbitrary:link-123','primary-agent'])('builds a validated opaque public link %s',linkId=>{expect(Reflect.get(H,'elevenLabsWebPublicPath')).toBeTypeOf('function');const path=Reflect.get(H,'elevenLabsWebPublicPath')(linkId);expect(path).toBe('/parla/'+encodeURIComponent(linkId));expect(C.isElevenLabsWebLinkCurrent({scope:{tenantId:'tenant-a',ownerId:'owner-a',agentId:'runtime-agent'},linkId,url:'https://forge.example'+path,createdAt:'2026-10-08T10:00:00Z'},{tenantId:'tenant-a',ownerId:'owner-a',agentId:'runtime-agent'},'https://forge.example')).toBe(true);});
it.each(['','../link','a?bypass','short','a bbbbbbbb','untrusted/link-id'])('rejects invalid opaque public link %s',linkId=>{expect(Reflect.get(H,'elevenLabsWebPublicPath')).toBeTypeOf('function');expect(()=>Reflect.get(H,'elevenLabsWebPublicPath')(linkId)).toThrow();});
