import { describe, expect, it } from 'vitest';
import * as Agent from '../../src/agent/index.js';
import * as Router from '../../src/model-router/index.js';
import * as Http from '../../src/http/index.js';
const identity={managementAgentId:'synthetic-master',runtimeAgentId:'synthetic-runtime',vaultAgentId:71};
const scope={agentId:identity.runtimeAgentId,ownerId:'synthetic-owner',tenantId:'synthetic-tenant'};
const settings={capability:'agent-core',function:'reasoning',catalogVersion:'synthetic-catalog',requirements:{tools:false,stream:false,structuredOutput:false},mode:'single' as const,descriptor:{provider:'openai',modelId:'synthetic-model',protocol:'chat-completions' as const,adapterId:'synthetic-adapter'}};
const configuration={schemaVersion:1 as const,identity,configVersion:2,selections:[{slotId:'agent_classifier',settings}],provenance:{scope,bindings:[{slotId:'agent_classifier',origin:'custom' as const}]}};
const base={action:'apply-config' as const,requestId:'synthetic-request-0001',desiredVersion:2};
const command={...base,modelConfiguration:configuration,modelExpectedSourceVersion:'synthetic-source-1'};
const parse=(input:unknown)=>Agent.AgentManagementCommandSchema.safeParse(input).success;
const same=(a:unknown,b:unknown)=>Agent.sameAgentCommand(a as Agent.AgentManagementCommand,b as Agent.AgentManagementCommand);
describe('Private Master configuration command',()=>{
 it('D01 carries canonical configuration on the existing endpoint',()=>{expect(Router.AgentModelsConfigurationWithProvenanceSchema.safeParse(configuration).success).toBe(true);expect(parse(command)).toBe(true);expect(Http.agentCommandContract.bodySchema.parse(command)).toEqual(command);expect(parse(base)).toBe(true);});
 it('D02 changed model selection is not a replay even with equal version/key',()=>expect(same(command,{...command,modelConfiguration:{...configuration,selections:[{...configuration.selections[0],settings:{...settings,descriptor:{...settings.descriptor,modelId:'synthetic-other'}}}]}})).toBe(false));
 it('D03 absence of configuration differs from explicit configuration',()=>expect(same(command,base)).toBe(false));
 it('D04 changed observed generation is not a replay',()=>expect(same(command,{...command,modelExpectedSourceVersion:'synthetic-source-2'})).toBe(false));
 it('D05 equivalent detached configuration is a replay',()=>expect(same(command,structuredClone(command))).toBe(true));
 it.each([1,3])('D06 configuration version %s must equal desiredVersion',configVersion=>expect(parse({...command,modelConfiguration:{...configuration,configVersion}})).toBe(false));
 it.each([{modelExpectedSourceVersion:undefined},{modelExpectedSourceVersion:' '},{modelConfiguration:undefined},{modelBootstrap:{expectedSourceVersion:'different',expectedAbsent:true}}])('D07 rejects missing or inconsistent generation %j',patch=>expect(parse({...command,...patch})).toBe(false));
 it('D08 bootstrap and explicit configuration use the same observed generation',()=>expect(parse({...command,modelBootstrap:{expectedSourceVersion:command.modelExpectedSourceVersion,expectedAbsent:true}})).toBe(true));
 it.each([{identity:{...identity,vaultAgentId:undefined}},{provenance:undefined},{provenance:{scope:{...scope,agentId:'other'},bindings:configuration.provenance.bindings}},{selections:[]},{selections:[configuration.selections[0],configuration.selections[0]]},{context:{}},{selections:[{...configuration.selections[0],slotId:'unregistered'}]},{selections:[{...configuration.selections[0],settings:{...settings,capability:'other'}}]}])('D09 canonical authority rejects invalid config %j',patch=>expect(parse({...command,modelConfiguration:{...configuration,...patch}})).toBe(false));
 it.each(['start','stop','restart','reload'])('D10 %s cannot carry a model configuration',action=>expect(parse({...command,action})).toBe(false));
 it('D11 binding origin remains part of command identity',()=>{const source={identity:{managementAgentId:'synthetic-parent',runtimeAgentId:'synthetic-parent-runtime',vaultAgentId:72},sourceVersion:1};const changed={...configuration,provenance:{scope,bindings:[{slotId:'agent_classifier',origin:'master',source}]}};expect(same(command,{...command,modelConfiguration:changed})).toBe(false);});
 it('D12 different tenant does not replay another authority',()=>expect(same(command,{...command,modelConfiguration:{...configuration,provenance:{...configuration.provenance,scope:{...scope,tenantId:'other'}}}})).toBe(false));
 it('D13 exact producer request can be checked against fresh source and route',()=>{const helper=Reflect.get(Router,'isAgentModelCommandSourceCurrent');expect(helper).toBeTypeOf('function');const check=helper as (command:unknown,source:unknown)=>boolean;expect(check(command,{identity,scope,sourceVersion:'synthetic-source-1'})).toBe(true);for(const patch of [{identity:{...identity,vaultAgentId:72}},{scope:{...scope,ownerId:'other'}},{scope:{...scope,tenantId:'other'}},{sourceVersion:'changed'}])expect(check(command,{identity,scope,sourceVersion:'synthetic-source-1',...patch})).toBe(false);expect(check(base,{identity,scope,sourceVersion:'synthetic-source-1'})).toBe(false);});
});

it.each([{function:'tts'},{requirements:{tools:true,stream:false,structuredOutput:false}},{mode:'automatic',tiers:{standard:settings.descriptor,advanced:settings.descriptor,reasoning:settings.descriptor},fallback:settings.descriptor,descriptor:undefined}])('D14 rejects registered slot with wrong settings %j',patch=>expect(parse({...command,modelConfiguration:{...configuration,selections:[{slotId:'agent_classifier',settings:{...settings,...patch}}]}})).toBe(false));
it('D15 selection/binding and object property order do not change command identity',()=>{const extra={slotId:'security_rules',settings:{...settings,capability:'security',requirements:{tools:false,stream:false,structuredOutput:true}}};const c={...command,modelConfiguration:{...configuration,selections:[configuration.selections[0],extra],provenance:{scope,bindings:[...configuration.provenance.bindings,{slotId:extra.slotId,origin:'custom' as const}]}}};expect(parse(c)).toBe(true);const reordered={...c,modelConfiguration:{...c.modelConfiguration,selections:[...c.modelConfiguration.selections].reverse(),provenance:{bindings:[...c.modelConfiguration.provenance.bindings].reverse(),scope:{tenantId:scope.tenantId,agentId:scope.agentId,ownerId:scope.ownerId}}}};expect(same(c,reordered)).toBe(true);});
it('D16 apply confirmation requires the actual configuration carried by the command',()=>{const now=new Date('2026-10-09T06:52:00Z');const result={ok:true,agentId:identity.managementAgentId,identity,action:'apply-config',requestId:command.requestId,replayed:false,outcome:'ok',requestedVersion:2,versions:{desired:2,applied:2,failed:null},results:[{target:{kind:'runtime',targetId:identity.runtimeAgentId},outcome:'ok'}],completedAt:now.toISOString()};const evidence={identity,configVersion:2,requestId:command.requestId,observedAt:now.toISOString(),selections:[{slotId:'agent_classifier',capability:'agent-core',function:'reasoning',tier:'primary',descriptor:settings.descriptor}]};expect(Router.isAgentModelApplyConfirmed(configuration,command,result,evidence,now)).toBe(true);const other={...command,modelConfiguration:{...configuration,selections:[{slotId:'agent_classifier',settings:{...settings,descriptor:{...settings.descriptor,modelId:'synthetic-other'}}}]}};expect(Router.isAgentModelApplyConfirmed(configuration,other,result,evidence,now)).toBe(false);const otherOrigin={...command,modelConfiguration:{...configuration,provenance:{scope,bindings:[{slotId:'agent_classifier',origin:'master',source:{identity:{managementAgentId:'synthetic-parent',runtimeAgentId:'synthetic-parent-runtime',vaultAgentId:72},sourceVersion:1}}]}}};expect(Router.isAgentModelApplyConfirmed(configuration,otherOrigin,result,evidence,now)).toBe(false);});

it('D17 an unregistered slot is rejected with otherwise coherent provenance',()=>{const value={...configuration,selections:[{slotId:'unregistered',settings}],provenance:{scope,bindings:[{slotId:'unregistered',origin:'custom' as const}]}};expect(Router.AgentModelsConfigurationWithProvenanceSchema.safeParse(value).success).toBe(true);expect(parse({...command,modelConfiguration:value})).toBe(false);});

it('D18 a registered single slot rejects a valid automatic shape',()=>{const automatic={capability:settings.capability,function:settings.function,catalogVersion:settings.catalogVersion,requirements:settings.requirements,mode:'automatic',tiers:{standard:settings.descriptor,advanced:settings.descriptor,reasoning:settings.descriptor},fallback:settings.descriptor};expect(Router.CapabilityModelSettingsSchema.safeParse(automatic).success).toBe(true);expect(parse({...command,modelConfiguration:{...configuration,selections:[{slotId:'agent_classifier',settings:automatic}]}})).toBe(false);});
