import {expect,it} from 'vitest';
import * as C from '../../src/capability/index.js';
import {ElevenLabsWebLinkSchema,ElevenLabsWebAdmissionSnapshotSchema,ElevenLabsWebViewerSchema,ElevenLabsWebSessionRequestSchema,ElevenLabsWebSessionResultSchema,isElevenLabsWebLinkCurrent,canAdmitElevenLabsWebViewer,isElevenLabsWebSessionCurrent} from '../../src/capability/agent-elevenlabs/web-session.js';
const scope={tenantId:'tenant-a',ownerId:'owner-a',agentId:'arbitrary-heir'};
const origin='https://forge.example';
const link={scope,linkId:'synthetic-link',url:origin+'/parla/synthetic-link',createdAt:'2026-10-08T10:00:00Z'};
const mapping={scope,providerAgentId:'agent_synthetic',origin:'provisioned',createdAt:'2026-10-08T10:00:00Z',appliedConfigVersion:3};
const policy={scope,version:2,access:'owner',paused:false};
const provider={scope,mapping,desiredState:'active',observedAt:'2026-10-08T10:29:00Z',channel:{channelId:'elevenlabs-web',kind:'web',state:'loaded',loaded:true,readiness:'ready'}};
const snapshot={policy,link,provider,lifecycle:'active',invitation:null,invitationRevision:null};
const owner={kind:'authenticated',userId:'person-owner',owner:{tenantId:'tenant-a',ownerId:'owner-a'}};
const guest={kind:'anonymous'};
const recipient={kind:'authenticated',userId:'person-invited',owner:null};
const invitation={invitationId:'synthetic-invitation',scope,revision:4,recipientUserId:'person-invited',createdAt:'2026-10-08T10:00:00Z',expiresAt:'2026-10-08T11:00:00Z',revokedAt:null};
const invited={...snapshot,policy:{...policy,access:'invited'},invitation,invitationRevision:4};
const now=new Date('2026-10-08T10:30:00Z');
const request={requestId:'synthetic-mint',scope,linkId:link.linkId,viewer:owner};
// Synthetic bearer artifact only; no provider request or credential is used.
const result={ok:true,requestId:request.requestId,scope,link,policyVersion:2,mapping,viewer:owner,invitation:null,invitationRevision:null,issuedAt:'2026-10-08T10:29:00Z',expiresAt:'2026-10-08T10:44:00Z',signedUrl:'wss://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_synthetic&conversation_signature=synthetic-only'};
const admit=(state:unknown=snapshot,viewer:unknown=owner,expected:unknown=scope,at=now)=>canAdmitElevenLabsWebViewer(state,expected,viewer,origin,at);
const current=(response:unknown=result,state:unknown=snapshot,viewer:unknown=owner,command:unknown=request,at=now)=>isElevenLabsWebSessionCurrent(command,response,state,viewer,origin,at);
it('exports the actual admission and session contracts',()=>{expect(C).toHaveProperty('canAdmitElevenLabsWebViewer',canAdmitElevenLabsWebViewer);expect(C).toHaveProperty('ElevenLabsWebSessionResultSchema',ElevenLabsWebSessionResultSchema);});
it('accepts a persisted same-origin speaking link',()=>expect(isElevenLabsWebLinkCurrent(link,scope,origin)).toBe(true));
it.each(['tenantId','ownerId','agentId'])('rejects link scope %s',key=>expect(isElevenLabsWebLinkCurrent(link,{...scope,[key]:'other'},origin)).toBe(false));
it.each(['https://provider.example/parla/synthetic-link','http://forge.example/parla/synthetic-link',origin+'/parla/other-link',origin+'/parla/synthetic-link?bypass=true',origin+'/parla/synthetic-link#fragment','https://user:pass@forge.example/parla/synthetic-link'])('rejects unsafe or mismatched authoritative link',url=>expect(isElevenLabsWebLinkCurrent({...link,url},scope,origin)).toBe(false));
it.each(['http://forge.example',origin+'/other',origin+'?x=y','invalid'])('rejects invalid configured origin',value=>expect(isElevenLabsWebLinkCurrent(link,scope,value)).toBe(false));
it('admits the server-authenticated owner',()=>expect(admit()).toBe(true));
it('admits anonymous only with explicit public policy',()=>{expect(admit({...snapshot,policy:{...policy,access:'public'}},guest)).toBe(true);expect(admit(snapshot,guest)).toBe(false);expect(admit(invited,guest)).toBe(false);});
it('admits the authenticated current invitation recipient',()=>expect(admit(invited,recipient)).toBe(true));
it('keeps owner access under invited and public policy',()=>{expect(admit(invited)).toBe(true);expect(admit({...snapshot,policy:{...policy,access:'public'}})).toBe(true);});
it.each(['tenantId','ownerId'])('rejects false owner membership %s',key=>expect(admit(snapshot,{...owner,owner:{...owner.owner,[key]:'other'}})).toBe(false));
it('rejects an authenticated stranger under owner policy',()=>expect(admit(snapshot,recipient)).toBe(false));
it.each(['tenantId','ownerId','agentId'])('rejects resolved admission scope %s',key=>expect(admit(snapshot,owner,{...scope,[key]:'other'})).toBe(false));
it.each(['archived','removed','unavailable'])('denies lifecycle %s',lifecycle=>expect(admit({...snapshot,lifecycle})).toBe(false));
it('denies Web pause without changing the provider mapping',()=>{expect(admit({...snapshot,policy:{...policy,paused:true}})).toBe(false);expect(snapshot.provider.mapping).toEqual(mapping);});
it('denies paused provider',()=>expect(admit({...snapshot,provider:{...provider,desiredState:'paused'}})).toBe(false));
it.each(['unknown','paused','stopped','error'])('denies provider channel %s',state=>{const loaded=state==='unknown'?null:state==='error'?false:false;expect(admit({...snapshot,provider:{...provider,observedAt:state==='unknown'?null:provider.observedAt,channel:{...provider.channel,state,loaded}}})).toBe(false);});
it.each(['unknown','not-ready'])('denies unready provider %s',readiness=>expect(admit({...snapshot,provider:{...provider,channel:{...provider.channel,readiness}}})).toBe(false));
it('denies absent provider mapping',()=>expect(admit({...snapshot,provider:{...provider,mapping:null,observedAt:null,channel:{...provider.channel,state:'unknown',loaded:null,readiness:'unknown'}}})).toBe(false));
it('denies future link and provider evidence',()=>{expect(admit({...snapshot,link:{...link,createdAt:'2026-10-08T10:31:00Z'}})).toBe(false);expect(admit({...snapshot,provider:{...provider,observedAt:'2026-10-08T10:31:00Z'}})).toBe(false);});
it('denies another invitation person and revision',()=>{expect(admit(invited,{...recipient,userId:'stranger'})).toBe(false);expect(admit({...invited,invitationRevision:5},recipient)).toBe(false);});
it('never uses a valid invitation under owner-only policy',()=>expect(admit({...invited,policy},recipient)).toBe(false));
it('rejects unpaired and foreign invitation evidence',()=>{expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse({...invited,invitationRevision:null}).success).toBe(false);expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse({...invited,invitation:{...invitation,scope:{...scope,agentId:'other-agent'}}}).success).toBe(false);});
it('denies expired, revoked and absent invitations',()=>{expect(admit({...invited,invitation:{...invitation,expiresAt:now.toISOString()}},recipient)).toBe(false);expect(admit({...invited,invitation:{...invitation,revokedAt:'2026-10-08T10:20:00Z'}},recipient)).toBe(false);expect(admit({...invited,invitation:null,invitationRevision:null},recipient)).toBe(false);});
it.each([null,{}, {...owner,owner:{...owner.owner,extra:true}},{kind:'authenticated',userId:'',owner:null},{...owner,role:'sa'}])('denies malformed viewer',viewer=>expect(admit(snapshot,viewer)).toBe(false));
it('denies malformed snapshot and clock',()=>{expect(admit({})).toBe(false);expect(admit(snapshot,owner,scope,new Date('invalid'))).toBe(false);});
it.each(['primary','arbitrary-heir','sibling-b'])('supports arbitrary runtime alias %s independently of management names',agentId=>{const alias={...scope,agentId};const state={...snapshot,policy:{...policy,scope:alias},link:{...link,scope:alias},provider:{...provider,scope:alias,mapping:{...mapping,scope:alias}}};expect(admit(state,owner,alias)).toBe(true);});
it('accepts a current server-issued session for exactly its request and viewer',()=>expect(current()).toBe(true));
it('invalidates mint completion after pause, archive or policy change',()=>{expect(current(result,{...snapshot,policy:{...policy,paused:true}})).toBe(false);expect(current(result,{...snapshot,lifecycle:'archived'})).toBe(false);expect(current(result,{...snapshot,policy:{...policy,version:3}})).toBe(false);expect(current(result,{...snapshot,policy:{...policy,access:'public',version:3}})).toBe(false);});
it.each(['providerAgentId','origin','createdAt','appliedConfigVersion'])('invalidates mint after mapping %s changes',key=>{const values={providerAgentId:'agent_other',origin:'adopted',createdAt:'2026-10-08T10:01:00Z',appliedConfigVersion:4};expect(current(result,{...snapshot,provider:{...provider,mapping:{...mapping,[key]:values[key as keyof typeof values]}}})).toBe(false);});
it('invalidates mint after link replacement',()=>expect(current(result,{...snapshot,link:{...link,linkId:'replacement-link',url:origin+'/parla/replacement-link'}})).toBe(false));
it('invalidates request and viewer substitution',()=>{expect(current({...result,requestId:'other-request'})).toBe(false);expect(current(result,snapshot,{...owner,userId:'another-owner'})).toBe(false);expect(current(result,snapshot,owner,{...request,viewer:recipient})).toBe(false);expect(current(result,snapshot,owner,{...request,linkId:'other-link'})).toBe(false);});
it.each(['tenantId','ownerId','agentId'])('invalidates result scope %s',key=>expect(current({...result,scope:{...scope,[key]:'other'}})).toBe(false));
it('invalidates a minted invite session after revoke, expiry or reissue',()=>{const command={...request,viewer:recipient};const response={...result,viewer:recipient,invitation,invitationRevision:4};expect(current(response,invited,recipient,command)).toBe(true);expect(current(response,{...invited,invitation:{...invitation,revokedAt:'2026-10-08T10:20:00Z'}},recipient,command)).toBe(false);expect(current(response,{...invited,invitation:{...invitation,invitationId:'reissued-invitation'}},recipient,command)).toBe(false);expect(current(response,invited,recipient,command,new Date(invitation.expiresAt))).toBe(false);});
it('rejects session expiry, future issuance and invalid clock',()=>{expect(current({...result,expiresAt:now.toISOString()})).toBe(false);expect(current({...result,issuedAt:'2026-10-08T10:31:00Z',expiresAt:'2026-10-08T10:44:00Z'})).toBe(false);expect(current(result,snapshot,owner,request,new Date('invalid'))).toBe(false);});
it.each(['wss://evil.example/v1/convai/conversation?agent_id=agent_synthetic&conversation_signature=synthetic-only','https://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_synthetic&conversation_signature=synthetic-only','wss://api.elevenlabs.io/other?agent_id=agent_synthetic&conversation_signature=synthetic-only','wss://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_other&conversation_signature=synthetic-only','wss://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_synthetic','wss://api.elevenlabs.io/v1/convai/conversation?agent_id=agent_synthetic&agent_id=agent_other&conversation_signature=synthetic-only'])('rejects invalid synthetic provider connection artifact',signedUrl=>expect(ElevenLabsWebSessionResultSchema.safeParse({...result,signedUrl}).success).toBe(false));
it('rejects malformed signed URL without throwing',()=>{expect(()=>ElevenLabsWebSessionResultSchema.safeParse({...result,signedUrl:'invalid'})).not.toThrow();expect(ElevenLabsWebSessionResultSchema.safeParse({...result,signedUrl:'invalid'}).success).toBe(false);});
it('rejects an overlong or inverted mint window',()=>{expect(ElevenLabsWebSessionResultSchema.safeParse({...result,expiresAt:'2026-10-08T10:45:01Z'}).success).toBe(false);expect(ElevenLabsWebSessionResultSchema.safeParse({...result,expiresAt:result.issuedAt}).success).toBe(false);});
it.each([['link',ElevenLabsWebLinkSchema,link],['snapshot',ElevenLabsWebAdmissionSnapshotSchema,snapshot],['viewer',ElevenLabsWebViewerSchema,owner],['request',ElevenLabsWebSessionRequestSchema,request],['result',ElevenLabsWebSessionResultSchema,result]] as const)('rejects undeclared %s fields',(_name,schema,fixture)=>expect(schema.safeParse({...fixture,extra:true}).success).toBe(false));
it('rejects mismatched snapshot scopes and non-Web channel',()=>{expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse({...snapshot,link:{...link,scope:{...scope,ownerId:'other'}}}).success).toBe(false);expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse({...snapshot,provider:{...provider,scope:{...scope,ownerId:'other'},mapping:{...mapping,scope:{...scope,ownerId:'other'}}}}).success).toBe(false);expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse({...snapshot,provider:{...provider,channel:{...provider.channel,kind:'voice'}}}).success).toBe(false);});
it('rejects foreign or unpaired mint evidence',()=>{expect(ElevenLabsWebSessionResultSchema.safeParse({...result,scope:{...scope,ownerId:'other'}}).success).toBe(false);expect(ElevenLabsWebSessionResultSchema.safeParse({...result,invitationRevision:4}).success).toBe(false);});
it('rejects malformed session correlation inputs',()=>{expect(current({})).toBe(false);expect(current(result,snapshot,owner,{})).toBe(false);});

it.each(['owner','invited','public'])('C5 explicit off denies %s new sessions without changing the stable link/provider',access=>{
  const state={...invited,policy:{...policy,access,enabled:false}};
  expect(ElevenLabsWebAdmissionSnapshotSchema.safeParse(state).success).toBe(true);
  expect(admit(state)).toBe(false); expect(admit(state,recipient)).toBe(false); expect(admit(state,guest)).toBe(false);
  expect(isElevenLabsWebLinkCurrent(state.link,scope,origin)).toBe(true);
  expect(state.provider.mapping).toEqual(mapping);
});
it('C5 enabled active admits the legacy owner and pause stays separate',()=>{
  expect(admit({...snapshot,policy:{...policy,enabled:true}})).toBe(true);
  expect(admit(snapshot)).toBe(true);
  expect(admit({...snapshot,policy:{...policy,enabled:true,paused:true}})).toBe(false);
  expect(admit({...snapshot,policy:{...policy,enabled:false,paused:false}})).toBe(false);
});
it('C5 disabling during mint prevents delivery of a new session without retroactively revoking an issued bearer',()=>{
  expect(current(result,{...snapshot,policy:{...policy,enabled:true}})).toBe(true);
  expect(current(result,{...snapshot,policy:{...policy,enabled:false}})).toBe(false);
  expect(result.signedUrl).toContain('synthetic-only');
});
