import {it,expect} from 'vitest';
import * as capability from '../../src/capability/index.js';
import {ElevenLabsWebPolicySchema,ElevenLabsWebPolicyChangeSchema,ElevenLabsWebPolicyResultSchema,ElevenLabsWebInvitationSchema,isElevenLabsWebPolicyResultCurrent,isElevenLabsWebInvitationCurrent} from '../../src/capability/agent-elevenlabs/web-channel.js';
const scope={tenantId:'tenant-a',ownerId:'owner-a',agentId:'arbitrary-heir'};
const policy={scope,version:2,access:'invited',paused:false};
const change={requestId:'synthetic-change',scope,expectedVersion:1,access:'invited',paused:false};
const result={ok:true,requestId:'synthetic-change',replayed:false,policy};
const invitation={invitationId:'synthetic-invitation',scope,revision:3,recipientUserId:'person-a',createdAt:'2026-10-08T10:00:00Z',expiresAt:'2026-10-08T11:00:00Z',revokedAt:null};
const now=new Date('2026-10-08T10:30:00Z');
const valid=(record:unknown=invitation,expectedScope:unknown=scope,person:unknown='person-a',revision:unknown=3,at=now)=>isElevenLabsWebInvitationCurrent(record,expectedScope,person,revision,at);
it('exports the actual canonical foundation through capability',()=>{expect(capability).toHaveProperty('ElevenLabsWebPolicySchema',ElevenLabsWebPolicySchema);expect(capability).toHaveProperty('isElevenLabsWebInvitationCurrent',isElevenLabsWebInvitationCurrent);});
it.each(['owner','invited','public'])('validates Web policy mode %s without changing provider state',access=>{expect(ElevenLabsWebPolicySchema.safeParse({...policy,access}).success).toBe(true);expect(ElevenLabsWebPolicySchema.safeParse({...policy,access,desiredState:'active'}).success).toBe(false);});
it.each([['policy',ElevenLabsWebPolicySchema,policy],['change',ElevenLabsWebPolicyChangeSchema,change],['result',ElevenLabsWebPolicyResultSchema,result],['invitation',ElevenLabsWebInvitationSchema,invitation]] as const)('rejects unknown fields in %s',(_name,schema,fixture)=>expect(schema.safeParse({...fixture,extra:'synthetic-only'}).success).toBe(false));
it.each([null,{}, {...policy,access:'anyone'}, {...policy,version:0},{...policy,paused:'false'}, {...policy,scope:{...scope,tenantId:''}}])('rejects invalid policy %j',fixture=>expect(ElevenLabsWebPolicySchema.safeParse(fixture).success).toBe(false));
it.each([['same first apply',false],['idempotent replay',true]] as const)('correlates %s',(_name,replayed)=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,replayed})).toBe(true));
it.each(['tenantId','ownerId','agentId'] as const)('rejects policy readback for another %s',key=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,policy:{...policy,scope:{...scope,[key]:'different'}}})).toBe(false));
it.each([1,3,4])('rejects policy readback version %s instead of the next revision',version=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,policy:{...policy,version}})).toBe(false));
it('rejects another request ID',()=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,requestId:'other-change'})).toBe(false));
it('rejects another access mode',()=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,policy:{...policy,access:'public'}})).toBe(false));
it('rejects another pause outcome',()=>expect(isElevenLabsWebPolicyResultCurrent(change,{...result,policy:{...policy,paused:true}})).toBe(false));
it.each([[{},result],[change,{}],[{...change,expectedVersion:0},result]])('rejects malformed policy correlation inputs', (request,response)=>expect(isElevenLabsWebPolicyResultCurrent(request,response)).toBe(false));
it('accepts the current recipient invitation in exactly its full scope',()=>expect(valid()).toBe(true));
it.each(['primary-agent','heir-agent','same-owner-sibling','arbitrary-123'])('handles arbitrary invited agent %s',agentId=>{const identity={...scope,agentId};expect(valid({...invitation,scope:identity},identity)).toBe(true);});
it.each(['tenantId','ownerId','agentId'] as const)('rejects an invitation in another %s',key=>expect(valid(invitation,{...scope,[key]:'other'})).toBe(false));
it('rejects another authenticated recipient',()=>expect(valid(invitation,scope,'person-b')).toBe(false));
it.each([undefined,null,''])('rejects absent or empty authenticated recipient',person=>expect(isElevenLabsWebInvitationCurrent(invitation,scope,person,3,now)).toBe(false));
it.each([1,2,4,0,1.5])('rejects invitation revision %s',revision=>expect(valid(invitation,scope,'person-a',revision)).toBe(false));
it('rejects a revoked invitation',()=>expect(valid({...invitation,revokedAt:'2026-10-08T10:15:00Z'})).toBe(false));
it.each(['2026-10-08T11:00:00Z','2026-10-08T11:01:00Z'])('rejects expiry at or before %s',at=>expect(valid(invitation,scope,'person-a',3,new Date(at))).toBe(false));
it('rejects an invitation not yet created',()=>expect(valid(invitation,scope,'person-a',3,new Date('2026-10-08T09:59:00Z'))).toBe(false));
it('rejects an invalid current clock',()=>expect(valid(invitation,scope,'person-a',3,new Date('invalid'))).toBe(false));
it.each([null,{}, {...invitation,scope:{...scope,ownerId:''}}, {...invitation,recipientUserId:''}, {...invitation,expiresAt:'invalid'},{...invitation,createdAt:invitation.expiresAt},{...invitation,createdAt:'2026-10-08T12:00:00Z'},{...invitation,revokedAt:'2026-10-08T09:00:00Z'}])('rejects malformed or contradictory invitation %j',record=>{expect(ElevenLabsWebInvitationSchema.safeParse(record).success).toBe(false);expect(valid(record)).toBe(false);});
it('rejects malformed expected scope',()=>expect(valid(invitation,{})).toBe(false));
