
import {describe,expect,it} from 'vitest';
import {ElevenLabsWebBrowserMetadataSchema as Metadata,ElevenLabsWebBrowserErrorResponseSchema as Failure,
  projectElevenLabsWebBrowserMetadata as project,isElevenLabsWebBrowserMetadataCurrent as current} from '../../../src/capability/agent-elevenlabs/web-browser.js';
const at='2026-10-10T12:00:00.000Z', now=new Date(at), origin='https://forge.example.test', linkId='metadata-link';
const scope={tenantId:'metadata-tenant',ownerId:'metadata-owner',agentId:'metadata-runtime'};
const viewer={kind:'authenticated',userId:'metadata-user',owner:{tenantId:scope.tenantId,ownerId:scope.ownerId}};
const snapshot={policy:{scope,version:3,access:'owner',paused:false,enabled:true},
 link:{scope,linkId,url:origin+'/parla/'+linkId,createdAt:at},
 provider:{scope,mapping:{scope,providerAgentId:'synthetic-metadata-agent',origin:'adopted',createdAt:at,appliedConfigVersion:3},desiredState:'active',observedAt:at,
  channel:{channelId:'metadata-channel',kind:'web',state:'loaded',loaded:true,readiness:'ready'}},
 lifecycle:'active',invitation:null,invitationRevision:null};
const evidence={linkId,expectedScope:scope,snapshot,viewer,configuredOrigin:origin,displayName:'Synthetic agent',observedAt:at,now};
const expected={ok:true,linkId,displayName:'Synthetic agent',state:'ready',observedAt:at};
const invitation={invitationId:'metadata-invitation',scope,revision:4,recipientUserId:'invited-user',createdAt:at,expiresAt:new Date(now.getTime()+3600000).toISOString(),revokedAt:null};
function invited(){return{...evidence,viewer:{kind:'authenticated',userId:invitation.recipientUserId,owner:null},snapshot:{...snapshot,policy:{...snapshot.policy,access:'invited'},invitation,invitationRevision:4}};}
describe('authorized browser metadata before Start',()=>{
 it('publishes only the admitted owner name, current link and truthful state',()=>{expect(project(evidence)).toEqual(expected);expect(Metadata.parse(expected)).toEqual(expected);});
 it('allows anonymous metadata only when the current policy is explicitly public',()=>{expect(project({...evidence,viewer:{kind:'anonymous'},snapshot:{...snapshot,policy:{...snapshot.policy,access:'public'}}})).toEqual(expected);expect(project({...evidence,viewer:{kind:'anonymous'}})).toBeNull();});
 it.each([{tenantId:'other-tenant',ownerId:scope.ownerId},{tenantId:scope.tenantId,ownerId:'other-owner'},null])('refuses a foreign authenticated owner membership %j',owner=>{expect(project({...evidence,viewer:{...viewer,owner}})).toBeNull();});
 it('admits the actual authenticated invitation recipient, never a pending or different person',()=>{expect(project(invited())).toEqual(expected);expect(project({...invited(),viewer:{kind:'authenticated',userId:'foreign-user',owner:null}})).toBeNull();expect(project({...invited(),snapshot:{...invited().snapshot,invitation:null,invitationRevision:null}})).toBeNull();});
 it.each(['revoked','expired','revision','future'])('rejects an invitation which is %s',reason=>{const input=invited();if(reason==='revoked')input.snapshot.invitation={...invitation,revokedAt:at} as typeof invitation;if(reason==='expired')input.now=new Date(invitation.expiresAt);if(reason==='revision')input.snapshot.invitationRevision=5;if(reason==='future')input.now=new Date(now.getTime()-1);expect(project(input)).toBeNull();});
 it.each(['scope','link','origin','http'])('does not disclose a name for substituted %s',field=>{const input={...evidence,expectedScope:field==='scope'?{...scope,ownerId:'foreign-owner'}:scope,linkId:field==='link'?'foreign-link':linkId,configuredOrigin:field==='origin'?'https://foreign.example.test':field==='http'?'http://forge.example.test':origin};expect(project(input)).toBeNull();});
 it.each(['archived','removed','unavailable'])('does not disclose an agent whose lifecycle is %s',lifecycle=>{expect(project({...evidence,snapshot:{...snapshot,lifecycle}})).toBeNull();});
 it.each([['paused',{paused:true},'paused'],['off',{enabled:false},'off'],['off and paused',{enabled:false,paused:true},'off']])('preserves %s without pretending it can start',(_label,change,state)=>{expect(project({...evidence,snapshot:{...snapshot,policy:{...snapshot.policy,...change as object}}})).toEqual({...expected,state});});
 it.each(['missing-mapping','unloaded','not-ready','old','future','missing-time','provider-paused'])('reports unavailable rather than ready for %s provider evidence',reason=>{const input=structuredClone(snapshot);if(reason==='missing-mapping'){input.provider.mapping=null as unknown as typeof input.provider.mapping;input.provider.channel={...input.provider.channel,state:'unknown',loaded:null as unknown as boolean,readiness:'unknown'};}if(reason==='unloaded'){input.provider.channel.loaded=false;input.provider.channel.state='stopped';}if(reason==='not-ready')input.provider.channel.readiness='not-ready';if(reason==='old')input.provider.observedAt=new Date(now.getTime()-60000).toISOString();if(reason==='future')input.provider.observedAt=new Date(now.getTime()+1).toISOString();if(reason==='missing-time'){input.provider.observedAt=null as unknown as string;input.provider.channel={...input.provider.channel,state:'unknown',loaded:null as unknown as boolean,readiness:'unknown'};}if(reason==='provider-paused')input.provider.desiredState='paused';expect(project({...evidence,snapshot:input})).toEqual({...expected,state:'unavailable'});});
 it.each([-1,60000,60001])('refuses stale or future owner evidence at age %d',age=>{expect(project({...evidence,observedAt:new Date(now.getTime()-age).toISOString()})).toBeNull();});
 it.each([null,'', ' '.repeat(3),'x'.repeat(201)])('does not invent a missing display name %j',displayName=>{expect(project({...evidence,displayName})).toBeNull();});
 it.each(['scope','viewer','mapping','signedUrl','invitation','agentIdentity','credentials'])('strictly excludes private %s from metadata and fixed errors',field=>{expect(Metadata.safeParse({...expected,[field]:{}}).success).toBe(false);expect(Failure.safeParse({ok:false,error:'access_denied',[field]:{}}).success).toBe(false);});
 it('metadata freshness checks exact link, current time and strict public shape',()=>{expect(current(expected,linkId,now)).toBe(true);expect(current(expected,'foreign-link',now)).toBe(false);expect(current(expected,linkId,new Date(now.getTime()+60000))).toBe(false);expect(current(expected,linkId,new Date(now.getTime()-1))).toBe(false);expect(current({...expected,signedUrl:'synthetic-only'},linkId,now)).toBe(false);expect(current(expected,linkId,new Date('invalid'))).toBe(false);});
 it('malformed server evidence never returns public metadata',()=>{expect(project({...evidence,snapshot:{}})).toBeNull();expect(project({...evidence,viewer:{kind:'authenticated',owner:viewer.owner}})).toBeNull();expect(project({...evidence,now:new Date('invalid')})).toBeNull();});
});
